pull_request_rules:
  - name: Apply commits on `master`
    conditions:
      - label=apply-on-master
    actions:
      backport:
        <<: &backport-action
          assignees:
            - "{{ author }}"
          body: |
            This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

            ----

            {{ body }}

            ----
            {{ cherry_pick_error }}

        branches:
          - master
        title: "[master] {{ title }}"
  - name: Apply commits on `4.6.x`
    conditions:
      - label=apply-on-4-6-x
    actions:
      backport:
        <<: *backport-action
        branches:
          - 4.6.x
        title: "[4.6.x] {{ title }}"
  - name: Apply commits on `4.7.x`
    conditions:
      - label=apply-on-4-7-x
    actions:
      backport:
        <<: *backport-action
        branches:
          - 4.7.x
        title: "[4.7.x] {{ title }}"
  - name: Apply commits on `4.8.x`
    conditions:
      - label=apply-on-4-8-x
    actions:
      backport:
        <<: *backport-action
        branches:
          - 4.8.x
        title: "[4.8.x] {{ title }}"
  - name: Apply commits on `4.9.x`
    conditions:
      - label=apply-on-4-9-x
    actions:
      backport:
        <<: *backport-action
        branches:
          - 4.9.x
        title: "[4.9.x] {{ title }}"
  - name: Apply commits on `4.10.x`
    conditions:
      - label=apply-on-4-10-x
    actions:
      backport:
        <<: *backport-action
        branches:
          - 4.10.x
        title: "[4.10.x] {{ title }}"


