pull_request_rules:
  - name: Apply commits on `master`
    conditions:
      - label=apply-on-master
    actions:
      backport:
        branches:
          - master
        assignees:
          - "{{ author }}"
        body: |
          This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

          ----

          {{ body }}

          ----
          {{ cherry_pick_error }}
        title: "[master] {{ title }}"
  - name: Apply commits on `3.21.x`
    conditions:
      - label=apply-on-3-21-x
    actions:
      backport:
        branches:
          - 3.21.x
        assignees:
          - "{{ author }}"
        body: |
          This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

          ----

          {{ body }}

          ----
          {{ cherry_pick_error }}
        title: "[3.21.x] {{ title }}"
  - name: Apply commits on `4.0.x`
    conditions:
      - label=apply-on-4-0-x
    actions:
      backport:
        branches:
          - 4.0.x
        assignees:
          - "{{ author }}"
        body: |
          This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

          ----

          {{ body }}

          ----
          {{ cherry_pick_error }}
        title: "[4.0.x] {{ title }}"
  - name: Apply commits on `3.20.x`
    conditions:
      - label=apply-on-3-20-x
    actions:
      backport:
        branches:
          - 3.20.x
        assignees:
          - "{{ author }}"
        body: |
          This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

          ----

          {{ body }}

          ----
          {{ cherry_pick_error }}
        title: "[3.20.x] {{ title }}"
  - name: Apply commits on `3.19.x`
    conditions:
      - label=apply-on-3-19-x
    actions:
      backport:
        branches:
          - 3.19.x
        assignees:
          - "{{ author }}"
        body: |
          This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

          ----

          {{ body }}

          ----
          {{ cherry_pick_error }}
        title: "[3.19.x] {{ title }}"
  - name: Apply commits on `3.18.x`
    conditions:
      - label=apply-on-3-18-x
    actions:
      backport:
        branches:
          - 3.18.x
        assignees:
          - "{{ author }}"
        body: |
          This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

          ----

          {{ body }}

          ----
          {{ cherry_pick_error }}
        title: "[3.18.x] {{ title }}"
