id=ciba-federation-am-authdevice-notifier
name=${project.name}
version=${project.version}
description=${project.description}
class=io.gravitee.am.authdevice.notifier.cibafederation.CibaFederationAuthenticationDeviceNotifier
type=authdevice-notifier
icon=ciba-federation.svg
