= Integration Tests

The AM integration tests run on Jest using Supertest to make calls to the AM APIs.
To run the tests from a terminal you need to be in the `gravitee-am-test` directory.

==== Build

Execute `npm install`. You usually only need to do this once, i.e. after cloning the AM repo or when dependencies have changed.

==== Run tests with default config

Executing `npm test` will run all the tests. To run individual tests use `npm test` followed by the name of the spec file.

    npm test my.jest.spec.ts

If you have Jest installed globally you can also run tests in the standard Jest way, although you will have to explicitly reference
one of the environment variable config files:

    jest --config=api/config/dev.config.js

==== Run tests against a specific environment

The file `api/config/dev.setup.js` contains environment variables used by the tests to interact with AM. Change these values to point to a
specific instance of AM.

==== Writing tests

Commands required for setting up and configuring AM for testing can be found in the `commands` directory. Each function returns an asynchronous
request to an AM endpoint which can be executed using standard ES6 promises, async/await syntax or Supertest's own provided callback functions.

===== async/await example

    describe("when an endpoint is called", () => {
        it('gives an expected response', async () => {
            let response = await createApplication(domainId, accessToken, app);
            expect(response.body.name).toEqual(app.name);
        }
    }

===== promise example

    describe("when an endpoint is called", () => {
        it('gives an expected response', () => {
            return createApplication(domainId, accessToken, app)
                .then(response => {
                    expect(response.body.name).toEqual(app.name);
                });
        }
    }

See the https://github.com/visionmedia/supertest[supertest] github page for a more detailed explanation of its api.