[libdefaults]
    default_realm = GRAVITEE.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    GRAVITEE.LOCAL = {
        kdc = kdc:88
        admin_server = kdc:749
    }

[domain_realm]
    .gravitee.local = GRAVITEE.LOCAL
    gravitee.local = GRAVITEE.LOCAL
