databaseChangeLog:
  - changeSet:
      id: 3.17.0
      author: GraviteeSource Team
      changes:
        ##########################
        # application_identities #
        ##########################
        - addColumn:
            tableName: application_identities
            columns:
              - column: { name: selection_rule, type: clob, constraints: { nullable: true } }
              - column: { name: priority, type: integer, constraints: { nullable: false }, defaultValue: -1 }

        ##############
        # flow_steps #
        ##############
        - addColumn:
            tableName: flow_steps
            columns:
              - column: { name: condition, type: clob, constraints: { nullable: true } }
