= Gateway

== System Requirements

=== JDK

Gravitee.io AM Gateway requires at least Java 8. Before you install Gravitee.io AM Gateway, please check your Java version :

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest JDK from the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java SE Download Site].

=== Repository

Default Gravitee.io AM Gateway distribution requires MongoDB 3.x to store management's configuration data.

NOTE: You can download MongoDB 3.x from the https://www.mongodb.org/downloads#production[MongoDB Download Site].

== Installing from the ZIP archive

Binaries are available from https://download.gravitee.io/graviteeio-am/components/gravitee-am-gateway/gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip.

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-am/components/gravitee-am-gateway/gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip -o gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip

Once file has been downloaded, you just have to unpack it in the right place.

[source,bash]
[subs="attributes"]
$ unzip gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip

And you can simply start up the gateway as follow:

[source,bash]
[subs="attributes"]
$ cd gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION
$ ./bin/gravitee

If everything goes well, you should see this kind of logs:

[source,bash]
[subs="attributes"]
...
16:21:01.995 [gravitee] [] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@1e1232cf{HTTP/1.1,[http/1.1]}{0.0.0.0:8092}
16:21:01.996 [gravitee] [] INFO  org.eclipse.jetty.server.Server - Started @19214ms
16:21:01.996 [gravitee] [] INFO  i.g.am.gateway.jetty.JettyHttpServer - HTTP Server is now started and listening on port 8092
...

By default, the gateway is listening on port *8092* and can be accessed from: _http://localhost:8092_.

== Directory structure

After successfully installed Gravitee.io AM Gateway, the `graviteeio-am-gateway` directory looks like this:

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Folder    |Description
|bin       |Startup/shutdown scripts
|config    |App configuration
|lib       |Libraries (gravitee.io AM libraries and third parties library)
|logs      |Gateway log files
|plugins   |Gateway plugins
|======================

