databaseChangeLog:
  - changeSet:
      id: 4.8.0-update-application-client-secrets-table
      author: GraviteeSource Team
      preConditions:
        onFail: MARK_RAN
        not:
          - columnExists:
              tableName: application_client_secrets
              columnName: expires_at
      changes:
        #############################
        # application_client_secrets #
        ############################
        - addColumn:
            tableName: application_client_secrets
            columns:
              - column: { name: expires_at, type: timestamp(6), constraints: { nullable: true } }
