databaseChangeLog:
  - changeSet:
      id: 3.9.0
      author: GraviteeSource Team
      changes:

        # Flows
        ########################
        - addColumn:
            tableName: flows
            columns:
              - column: { name: flow_order, type: int, constraints: { nullable: true } }
