databaseChangeLog:
  - changeSet:
      id: 3.10.0-add-self-service-account-settings
      author: GraviteeSource Team
      changes:

        # Domains
        ########################
        - addColumn:
            tableName: domains
            columns:
              - column: { name: self_service_account_settings, type: clob, constraints: { nullable: true } }
