= Gravitee.io AM Portal

This project was generated with https://github.com/angular/angular-cli[Angular CLI].

== Install

- Install https://github.com/nvm-sh/nvm[nvm]
- Install the Angular CLI
```
npm install -g @angular/cli
```
- Use with `nvm use` or install with `nvm install` the node version declared in `.nvmrc`
- Then install node modules with:
```
npm install
```

== Development server

Run `npm run serve` for a dev server. Navigate to `http://localhost:4200/`.
The app will automatically reload if you change any of the source files.

== Code scaffolding

Run `ng generate component component-name` to generate a new component.
You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

== Build

Run `npm run build` to build the project.
The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build.

== Running unit tests

Run `npm run test` to execute the unit tests via https://karma-runner.github.io[Karma].

== Running end-to-end tests

Run `npm run e2e` to execute the end-to-end tests via http://www.protractortest.org/[Protractor].

== Further help

To get more help on the Angular CLI use `ng help` or go check out the https://github.com/angular/angular-cli/blob/master/README.md[Angular CLI README].
