databaseChangeLog:
  - changeSet:
      id: 4.12.0-agent-applications-table
      author: GraviteeSource Team
      preConditions:
        - onFail: MARK_RAN
        - not:
            - tableExists:
                tableName: agent_applications
      changes:
        - createTable:
            tableName: agent_applications
            columns:
              - column: { name: application_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: { name: agent_type, type: nvarchar(64), constraints: { nullable: true } }

        - addPrimaryKey:
            constraintName: pk_agent_applications
            columnNames: application_id
            tableName: agent_applications

        - createIndex:
            columns:
              - column:
                  name: application_id
            indexName: idx_agent_applications_app
            tableName: agent_applications
            unique: true

        - createIndex:
            columns:
              - column:
                  name: agent_type
            indexName: idx_agent_applications_type
            tableName: agent_applications
            unique: false
