#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM alpine:3.8 AS build-env
MAINTAINER Gravitee Team <http://gravitee.io>

ARG GRAVITEEAM_VERSION=0

RUN apk add --update zip unzip

ADD ./gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip /tmp/
RUN unzip /tmp/gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip -d /tmp/


FROM graviteeio/java:8
MAINTAINER Gravitee Team <http://gravitee.io>

ENV GRAVITEEAM_HOME /opt/graviteeio-am-gateway

COPY --from=build-env /tmp/gravitee-am-gateway-standalone-* /opt/graviteeio-am-gateway/

RUN addgroup -g 1000 gravitee \
    && adduser -D -u 1000 -G gravitee -h ${GRAVITEEAM_HOME} gravitee \
    && chown -R gravitee:gravitee ${GRAVITEEAM_HOME}

USER 1000

WORKDIR ${GRAVITEEAM_HOME}

EXPOSE 8092
VOLUME ["/opt/gravitee-am-gateway/logs"]
CMD ["./bin/gravitee"]
