#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM graviteeio/java:21 as build-env
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEAM_VERSION=0
ARG JATTACH_VERSION=1.6

RUN apk update \
	&& apk add --update --no-cache zip unzip netcat-openbsd wget \
	&& wget --no-check-certificate -O /tmp/gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip https://download.gravitee.io/graviteeio-am/components/gravitee-am-gateway/gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip \
    && unzip /tmp/gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip -d /tmp/ \
    && rm /tmp/gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip

FROM eclipse-temurin:21.0.8_9-jdk-noble
LABEL maintainer="contact@graviteesource.com"

ENV GRAVITEEIO_HOME /opt/graviteeio-am-gateway
ENV LD_PRELOAD /usr/lib/libjemalloc.so.2

ARG JATTACH_VERSION=1.6

# Upgrade libc6
USER root
RUN apt-get update && \
    apt-get upgrade -y libc6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends libjemalloc2 build-essential wget ca-certificates && \
    wget -O /tmp/jattach.tar.gz https://github.com/apangin/jattach/archive/refs/tags/v${JATTACH_VERSION}.tar.gz && \
    tar -xf /tmp/jattach.tar.gz -C /tmp/ && \
    make -C /tmp/jattach-${JATTACH_VERSION} && \
    install -m 0755 /tmp/jattach-${JATTACH_VERSION}/jattach /usr/local/bin/jattach && \
    ln -s /usr/local/bin/jattach /usr/local/bin/jeattach && \
    ln -sf /usr/lib/$(dpkg-architecture --query DEB_BUILD_MULTIARCH)/libjemalloc.so.2 /usr/lib/libjemalloc.so.2 && \
    apt-get purge -y build-essential wget && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /tmp/jattach-${JATTACH_VERSION} /tmp/jattach.tar.gz

RUN groupmod --new-name graviteeio ubuntu && \
 adduser --disabled-password --no-create-home -uid 1001 graviteeio --ingroup graviteeio

COPY --from=build-env --chown=1001:1000 /tmp/gravitee-am-gateway-standalone-* /opt/graviteeio-am-gateway/

RUN if [ -x "${JAVA_HOME}/bin/jcmd" ]; then \
        ln -sf "${JAVA_HOME}/bin/jcmd" /usr/local/bin/jcmd; \
    else \
        echo "jcmd not found in ${JAVA_HOME}/bin" >&2; \
        exit 1; \
    fi

WORKDIR ${GRAVITEEIO_HOME}
EXPOSE 8092
ENTRYPOINT ["./bin/gravitee"]

USER graviteeio
