#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM alpine:3.22 AS build-env
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEAM_VERSION=0

RUN apk add --update zip unzip

ADD ./gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip /tmp/

RUN unzip /tmp/gravitee-am-gateway-standalone-${GRAVITEEAM_VERSION}.zip -d /tmp/

FROM graviteeio/java:21
LABEL maintainer="contact@graviteesource.com"

ENV GRAVITEE_AM_HOME /opt/graviteeio-am-gateway

COPY --from=build-env /tmp/gravitee-am-gateway-standalone-* /opt/graviteeio-am-gateway/

RUN addgroup -g 1000 graviteeio \
    && adduser -D -H -u 1001 graviteeio --ingroup graviteeio \
    && chgrp -R graviteeio ${GRAVITEE_AM_HOME} \
    && chmod -R g=u ${GRAVITEE_AM_HOME}

WORKDIR ${GRAVITEE_AM_HOME}

EXPOSE 8092

VOLUME ["/opt/graviteeio-am-gateway/logs"]

CMD ["./bin/gravitee"]

USER graviteeio
