# MAPI base only (MongoDB). Use with: helm -f am-mongodb-common.yaml -f am-mongodb-mapi.yaml
labels:
  environment: migration-test
  part-of: am-migration-tool

mongodb-replicaset:
  enabled: false

repositories:
  system-cluster: gateway
  management:
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee?serverSelectionTimeoutMS=30000"
      dbname: gravitee
  oauth2:
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee?serverSelectionTimeoutMS=30000"
      dbname: gravitee
  gateway:
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee?serverSelectionTimeoutMS=30000"
      dbname: gravitee

dataPlanes:
  - id: default
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee?serverSelectionTimeoutMS=30000"
      dbname: gravitee
  - id: dp1
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee-dp1?serverSelectionTimeoutMS=30000&authSource=gravitee"
      dbname: gravitee-dp1
  - id: dp2
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee-dp2?serverSelectionTimeoutMS=30000&authSource=gravitee"
      dbname: gravitee-dp2

api:
  enabled: false

gateway:
  enabled: false

license:
  accept: true
