# Gateway dp1 (MongoDB). Release: am-gateway-dp1. Port-forward: 8091.
labels:
  environment: migration-test
  part-of: am-migration-tool

mongodb-replicaset:
  enabled: false

repositories:
  system-cluster: gateway
  management:
    type: mongodb
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee?serverSelectionTimeoutMS=30000"
      dbname: gravitee
  oauth2:
    type: mongodb
    use-management-settings: false
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee?serverSelectionTimeoutMS=30000"
      dbname: gravitee
  gateway:
    type: mongodb
    use-management-settings: false
    dataPlane:
      id: dp1
      url: "http://localhost:8091"
    mongodb:
      uri: "mongodb://gravitee:gravitee-password@mongo-mongodb:27017/gravitee-dp1?serverSelectionTimeoutMS=30000&authSource=gravitee"
      dbname: gravitee-dp1

api:
  enabled: false

gateway:
  enabled: true
  replicaCount: 1
  services:
    sync:
      permissions: true
  image:
    repository: graviteeio/am-gateway
    tag: 4.10.0
    pullPolicy: IfNotPresent
  ingress:
    enabled: false

ui:
  enabled: false

license:
  accept: true
