# MAPI base only (PostgreSQL). Use with: helm -f am-postgres-common.yaml -f am-postgres-mapi.yaml
labels:
  environment: migration-test
  part-of: am-migration-tool

management:
  type: jdbc

jdbc:
  drivers:
    - https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar
    - https://repo1.maven.org/maven2/org/postgresql/r2dbc-postgresql/1.0.7.RELEASE/r2dbc-postgresql-1.0.7.RELEASE.jar

repositories:
  system-cluster: gateway
  management:
    type: jdbc
    jdbc:
      driver: postgresql
      host: postgres-postgresql
      port: 5432
      database: gravitee-am
      username: gravitee
      password: gravitee-password
  oauth2:
    type: jdbc
    jdbc:
      driver: postgresql
      host: postgres-postgresql
      port: 5432
      database: gravitee-am
      username: gravitee
      password: gravitee-password
  gateway:
    type: jdbc
    jdbc:
      driver: postgresql
      host: postgres-postgresql
      port: 5432
      database: gravitee-am
      username: gravitee
      password: gravitee-password

dataPlanes:
  - id: default
    type: jdbc
    jdbc:
      driver: postgresql
      host: postgres-postgresql
      port: 5432
      database: gravitee-am
      username: gravitee
      password: gravitee-password
  - id: dp1
    type: jdbc
    jdbc:
      driver: postgresql
      host: postgres-postgresql
      port: 5432
      database: gravitee-am-dp1
      username: gravitee
      password: gravitee-password
  - id: dp2
    type: jdbc
    jdbc:
      driver: postgresql
      host: postgres-postgresql
      port: 5432
      database: gravitee-am-dp2
      username: gravitee
      password: gravitee-password

api:
  enabled: false
  env:
    - name: LIQUIBASE_ANALYTICS_ENABLED
      value: "false"

gateway:
  enabled: false

license:
  accept: true
