/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
import type { Settings } from './Settings';
import { SettingsFromJSON, SettingsFromJSONTyped, SettingsToJSON, SettingsToJSONTyped } from './Settings';

/**
 *
 * @export
 * @interface AgentApplication
 */
export interface AgentApplication {
  /**
   *
   * @type {string}
   * @memberof AgentApplication
   */
  description?: string;
  /**
   *
   * @type {boolean}
   * @memberof AgentApplication
   */
  enabled?: boolean;
  /**
   *
   * @type {string}
   * @memberof AgentApplication
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof AgentApplication
   */
  name?: string;
  /**
   *
   * @type {Settings}
   * @memberof AgentApplication
   */
  settings?: Settings;
  /**
   *
   * @type {string}
   * @memberof AgentApplication
   */
  type?: AgentApplicationTypeEnum;
  /**
   *
   * @type {Date}
   * @memberof AgentApplication
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const AgentApplicationTypeEnum = {
  Web: 'WEB',
  Native: 'NATIVE',
  Browser: 'BROWSER',
  Service: 'SERVICE',
  ResourceServer: 'RESOURCE_SERVER',
} as const;
export type AgentApplicationTypeEnum = typeof AgentApplicationTypeEnum[keyof typeof AgentApplicationTypeEnum];

/**
 * Check if a given object implements the AgentApplication interface.
 */
export function instanceOfAgentApplication(value: object): value is AgentApplication {
  return true;
}

export function AgentApplicationFromJSON(json: any): AgentApplication {
  return AgentApplicationFromJSONTyped(json, false);
}

export function AgentApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentApplication {
  if (json == null) {
    return json;
  }
  return {
    description: json['description'] == null ? undefined : json['description'],
    enabled: json['enabled'] == null ? undefined : json['enabled'],
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    settings: json['settings'] == null ? undefined : SettingsFromJSON(json['settings']),
    type: json['type'] == null ? undefined : json['type'],
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  };
}

export function AgentApplicationToJSON(json: any): AgentApplication {
  return AgentApplicationToJSONTyped(json, false);
}

export function AgentApplicationToJSONTyped(value?: AgentApplication | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    description: value['description'],
    enabled: value['enabled'],
    id: value['id'],
    name: value['name'],
    settings: SettingsToJSON(value['settings']),
    type: value['type'],
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
  };
}
