/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AlertNotifier
 */
export interface AlertNotifier {
  /**
   *
   * @type {string}
   * @memberof AlertNotifier
   */
  configuration?: string;
  /**
   *
   * @type {Date}
   * @memberof AlertNotifier
   */
  createdAt?: Date;
  /**
   *
   * @type {boolean}
   * @memberof AlertNotifier
   */
  enabled?: boolean;
  /**
   *
   * @type {string}
   * @memberof AlertNotifier
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof AlertNotifier
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AlertNotifier
   */
  referenceId?: string;
  /**
   *
   * @type {string}
   * @memberof AlertNotifier
   */
  referenceType?: AlertNotifierReferenceTypeEnum;
  /**
   *
   * @type {string}
   * @memberof AlertNotifier
   */
  type?: string;
  /**
   *
   * @type {Date}
   * @memberof AlertNotifier
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const AlertNotifierReferenceTypeEnum = {
  Platform: 'PLATFORM',
  Domain: 'DOMAIN',
  Application: 'APPLICATION',
  Organization: 'ORGANIZATION',
  Environment: 'ENVIRONMENT',
  ProtectedResource: 'PROTECTED_RESOURCE',
} as const;
export type AlertNotifierReferenceTypeEnum = (typeof AlertNotifierReferenceTypeEnum)[keyof typeof AlertNotifierReferenceTypeEnum];

/**
 * Check if a given object implements the AlertNotifier interface.
 */
export function instanceOfAlertNotifier(value: object): value is AlertNotifier {
  return true;
}

export function AlertNotifierFromJSON(json: any): AlertNotifier {
  return AlertNotifierFromJSONTyped(json, false);
}

export function AlertNotifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertNotifier {
  if (json == null) {
    return json;
  }
  return {
    configuration: json['configuration'] == null ? undefined : json['configuration'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    enabled: json['enabled'] == null ? undefined : json['enabled'],
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    referenceId: json['referenceId'] == null ? undefined : json['referenceId'],
    referenceType: json['referenceType'] == null ? undefined : json['referenceType'],
    type: json['type'] == null ? undefined : json['type'],
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  };
}

export function AlertNotifierToJSON(json: any): AlertNotifier {
  return AlertNotifierToJSONTyped(json, false);
}

export function AlertNotifierToJSONTyped(value?: AlertNotifier | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    configuration: value['configuration'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    enabled: value['enabled'],
    id: value['id'],
    name: value['name'],
    referenceId: value['referenceId'],
    referenceType: value['referenceType'],
    type: value['type'],
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
  };
}
