/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 * A resource server this application may request an ID-JAG for.
 * @export
 * @interface ApplicationCrossAppAccessResourceServer
 */
export interface ApplicationCrossAppAccessResourceServer {
  /**
   * Identifier this application is registered with at the resource authorization server.
   * @type {string}
   * @memberof ApplicationCrossAppAccessResourceServer
   */
  clientId?: string;
  /**
   * Identifier of the resource server, as generated by AM on the trusted domain.
   * @type {string}
   * @memberof ApplicationCrossAppAccessResourceServer
   */
  resourceServerId?: string;
  /**
   * Identifier of the trusted domain the resource server belongs to. A hint used to resolve the resource server; the resource server identifier remains authoritative.
   * @type {string}
   * @memberof ApplicationCrossAppAccessResourceServer
   */
  trustDomainId?: string;
}

/**
 * Check if a given object implements the ApplicationCrossAppAccessResourceServer interface.
 */
export function instanceOfApplicationCrossAppAccessResourceServer(value: object): value is ApplicationCrossAppAccessResourceServer {
  return true;
}

export function ApplicationCrossAppAccessResourceServerFromJSON(json: any): ApplicationCrossAppAccessResourceServer {
  return ApplicationCrossAppAccessResourceServerFromJSONTyped(json, false);
}

export function ApplicationCrossAppAccessResourceServerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApplicationCrossAppAccessResourceServer {
  if (json == null) {
    return json;
  }
  return {
    clientId: json['clientId'] == null ? undefined : json['clientId'],
    resourceServerId: json['resourceServerId'] == null ? undefined : json['resourceServerId'],
    trustDomainId: json['trustDomainId'] == null ? undefined : json['trustDomainId'],
  };
}

export function ApplicationCrossAppAccessResourceServerToJSON(json: any): ApplicationCrossAppAccessResourceServer {
  return ApplicationCrossAppAccessResourceServerToJSONTyped(json, false);
}

export function ApplicationCrossAppAccessResourceServerToJSONTyped(
  value?: ApplicationCrossAppAccessResourceServer | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clientId: value['clientId'],
    resourceServerId: value['resourceServerId'],
    trustDomainId: value['trustDomainId'],
  };
}
