/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApplicationResourceResource,
  ApplicationResourceResourceFromJSON,
  ApplicationResourceResourceFromJSONTyped,
  ApplicationResourceResourceToJSON,
} from './ApplicationResourceResource';

/**
 *
 * @export
 * @interface ApplicationResourcesResource
 */
export interface ApplicationResourcesResource {
  /**
   *
   * @type {ApplicationResourceResource}
   * @memberof ApplicationResourcesResource
   */
  resourceResource?: ApplicationResourceResource;
}

export function ApplicationResourcesResourceFromJSON(json: any): ApplicationResourcesResource {
  return ApplicationResourcesResourceFromJSONTyped(json, false);
}

export function ApplicationResourcesResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationResourcesResource {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    resourceResource: !exists(json, 'resourceResource') ? undefined : ApplicationResourceResourceFromJSON(json['resourceResource']),
  };
}

export function ApplicationResourcesResourceToJSON(value?: ApplicationResourcesResource | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    resourceResource: ApplicationResourceResourceToJSON(value.resourceResource),
  };
}
