/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApplicationAdvancedSettings
 */
export interface ApplicationAdvancedSettings {
  /**
   *
   * @type {string}
   * @memberof ApplicationAdvancedSettings
   */
  agentCardUrl?: string;
  /**
   *
   * @type {boolean}
   * @memberof ApplicationAdvancedSettings
   */
  flowsInherited?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ApplicationAdvancedSettings
   */
  skipConsent?: boolean;
}

/**
 * Check if a given object implements the ApplicationAdvancedSettings interface.
 */
export function instanceOfApplicationAdvancedSettings(value: object): value is ApplicationAdvancedSettings {
  return true;
}

export function ApplicationAdvancedSettingsFromJSON(json: any): ApplicationAdvancedSettings {
  return ApplicationAdvancedSettingsFromJSONTyped(json, false);
}

export function ApplicationAdvancedSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationAdvancedSettings {
  if (json == null) {
    return json;
  }
  return {
    agentCardUrl: json['agentCardUrl'] == null ? undefined : json['agentCardUrl'],
    flowsInherited: json['flowsInherited'] == null ? undefined : json['flowsInherited'],
    skipConsent: json['skipConsent'] == null ? undefined : json['skipConsent'],
  };
}

export function ApplicationAdvancedSettingsToJSON(json: any): ApplicationAdvancedSettings {
  return ApplicationAdvancedSettingsToJSONTyped(json, false);
}

export function ApplicationAdvancedSettingsToJSONTyped(
  value?: ApplicationAdvancedSettings | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    agentCardUrl: value['agentCardUrl'],
    flowsInherited: value['flowsInherited'],
    skipConsent: value['skipConsent'],
  };
}
