/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
import type { ApplicationCrossAppAccessResourceServer } from './ApplicationCrossAppAccessResourceServer';
import {
  ApplicationCrossAppAccessResourceServerFromJSON,
  ApplicationCrossAppAccessResourceServerFromJSONTyped,
  ApplicationCrossAppAccessResourceServerToJSON,
  ApplicationCrossAppAccessResourceServerToJSONTyped,
} from './ApplicationCrossAppAccessResourceServer';

/**
 * Resource servers this application may request an ID-JAG for.
 * @export
 * @interface ApplicationCrossAppAccessSettings
 */
export interface ApplicationCrossAppAccessSettings {
  /**
   * Whether this application participates in Cross App Access.
   * @type {boolean}
   * @memberof ApplicationCrossAppAccessSettings
   */
  enabled?: boolean;
  /**
   * Resource servers this application may reach, one entry per resource server.
   * @type {Array<ApplicationCrossAppAccessResourceServer>}
   * @memberof ApplicationCrossAppAccessSettings
   */
  resourceServers?: Array<ApplicationCrossAppAccessResourceServer>;
}

/**
 * Check if a given object implements the ApplicationCrossAppAccessSettings interface.
 */
export function instanceOfApplicationCrossAppAccessSettings(value: object): value is ApplicationCrossAppAccessSettings {
  return true;
}

export function ApplicationCrossAppAccessSettingsFromJSON(json: any): ApplicationCrossAppAccessSettings {
  return ApplicationCrossAppAccessSettingsFromJSONTyped(json, false);
}

export function ApplicationCrossAppAccessSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationCrossAppAccessSettings {
  if (json == null) {
    return json;
  }
  return {
    enabled: json['enabled'] == null ? undefined : json['enabled'],
    resourceServers:
      json['resourceServers'] == null
        ? undefined
        : (json['resourceServers'] as Array<any>).map(ApplicationCrossAppAccessResourceServerFromJSON),
  };
}

export function ApplicationCrossAppAccessSettingsToJSON(json: any): ApplicationCrossAppAccessSettings {
  return ApplicationCrossAppAccessSettingsToJSONTyped(json, false);
}

export function ApplicationCrossAppAccessSettingsToJSONTyped(
  value?: ApplicationCrossAppAccessSettings | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    enabled: value['enabled'],
    resourceServers:
      value['resourceServers'] == null
        ? undefined
        : (value['resourceServers'] as Array<any>).map(ApplicationCrossAppAccessResourceServerToJSON),
  };
}
