/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApplicationIdentityProvider
 */
export interface ApplicationIdentityProvider {
  /**
   *
   * @type {string}
   * @memberof ApplicationIdentityProvider
   */
  identity?: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationIdentityProvider
   */
  selectionRule?: string;
  /**
   *
   * @type {number}
   * @memberof ApplicationIdentityProvider
   */
  priority?: number;
}

/**
 * Check if a given object implements the ApplicationIdentityProvider interface.
 */
export function instanceOfApplicationIdentityProvider(value: object): value is ApplicationIdentityProvider {
  return true;
}

export function ApplicationIdentityProviderFromJSON(json: any): ApplicationIdentityProvider {
  return ApplicationIdentityProviderFromJSONTyped(json, false);
}

export function ApplicationIdentityProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationIdentityProvider {
  if (json == null) {
    return json;
  }
  return {
    identity: json['identity'] == null ? undefined : json['identity'],
    selectionRule: json['selectionRule'] == null ? undefined : json['selectionRule'],
    priority: json['priority'] == null ? undefined : json['priority'],
  };
}

export function ApplicationIdentityProviderToJSON(json: any): ApplicationIdentityProvider {
  return ApplicationIdentityProviderToJSONTyped(json, false);
}

export function ApplicationIdentityProviderToJSONTyped(
  value?: ApplicationIdentityProvider | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    identity: value['identity'],
    selectionRule: value['selectionRule'],
    priority: value['priority'],
  };
}
