/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationEmailsResource,
    ApplicationEmailsResourceFromJSON,
    ApplicationEmailsResourceFromJSONTyped,
    ApplicationEmailsResourceToJSON,
} from './ApplicationEmailsResource';
import {
    ApplicationFlowsResource,
    ApplicationFlowsResourceFromJSON,
    ApplicationFlowsResourceFromJSONTyped,
    ApplicationFlowsResourceToJSON,
} from './ApplicationFlowsResource';
import {
    ApplicationFormsResource,
    ApplicationFormsResourceFromJSON,
    ApplicationFormsResourceFromJSONTyped,
    ApplicationFormsResourceToJSON,
} from './ApplicationFormsResource';
import {
    ApplicationMembersResource,
    ApplicationMembersResourceFromJSON,
    ApplicationMembersResourceFromJSONTyped,
    ApplicationMembersResourceToJSON,
} from './ApplicationMembersResource';
import {
    ApplicationResourcesResource,
    ApplicationResourcesResourceFromJSON,
    ApplicationResourcesResourceFromJSONTyped,
    ApplicationResourcesResourceToJSON,
} from './ApplicationResourcesResource';

/**
 * 
 * @export
 * @interface ApplicationResource
 */
export interface ApplicationResource {
    /**
     * 
     * @type {ApplicationFlowsResource}
     * @memberof ApplicationResource
     */
    flowsResource?: ApplicationFlowsResource;
    /**
     * 
     * @type {ApplicationMembersResource}
     * @memberof ApplicationResource
     */
    membersResource?: ApplicationMembersResource;
    /**
     * 
     * @type {ApplicationFormsResource}
     * @memberof ApplicationResource
     */
    formsResource?: ApplicationFormsResource;
    /**
     * 
     * @type {ApplicationResourcesResource}
     * @memberof ApplicationResource
     */
    resourcesResource?: ApplicationResourcesResource;
    /**
     * 
     * @type {ApplicationEmailsResource}
     * @memberof ApplicationResource
     */
    emailsResource?: ApplicationEmailsResource;
    /**
     * 
     * @type {any}
     * @memberof ApplicationResource
     */
    analyticsResource?: any;
}

export function ApplicationResourceFromJSON(json: any): ApplicationResource {
    return ApplicationResourceFromJSONTyped(json, false);
}

export function ApplicationResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flowsResource': !exists(json, 'flowsResource') ? undefined : ApplicationFlowsResourceFromJSON(json['flowsResource']),
        'membersResource': !exists(json, 'membersResource') ? undefined : ApplicationMembersResourceFromJSON(json['membersResource']),
        'formsResource': !exists(json, 'formsResource') ? undefined : ApplicationFormsResourceFromJSON(json['formsResource']),
        'resourcesResource': !exists(json, 'resourcesResource') ? undefined : ApplicationResourcesResourceFromJSON(json['resourcesResource']),
        'emailsResource': !exists(json, 'emailsResource') ? undefined : ApplicationEmailsResourceFromJSON(json['emailsResource']),
        'analyticsResource': !exists(json, 'analyticsResource') ? undefined : json['analyticsResource'],
    };
}

export function ApplicationResourceToJSON(value?: ApplicationResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flowsResource': ApplicationFlowsResourceToJSON(value.flowsResource),
        'membersResource': ApplicationMembersResourceToJSON(value.membersResource),
        'formsResource': ApplicationFormsResourceToJSON(value.formsResource),
        'resourcesResource': ApplicationResourcesResourceToJSON(value.resourcesResource),
        'emailsResource': ApplicationEmailsResourceToJSON(value.emailsResource),
        'analyticsResource': value.analyticsResource,
    };
}

