/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationScopeSettings
 */
export interface ApplicationScopeSettings {
    /**
     * 
     * @type {string}
     * @memberof ApplicationScopeSettings
     */
    scope?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationScopeSettings
     */
    defaultScope?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApplicationScopeSettings
     */
    scopeApproval?: number;
}

export function ApplicationScopeSettingsFromJSON(json: any): ApplicationScopeSettings {
    return ApplicationScopeSettingsFromJSONTyped(json, false);
}

export function ApplicationScopeSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationScopeSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'defaultScope': !exists(json, 'defaultScope') ? undefined : json['defaultScope'],
        'scopeApproval': !exists(json, 'scopeApproval') ? undefined : json['scopeApproval'],
    };
}

export function ApplicationScopeSettingsToJSON(value?: ApplicationScopeSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scope': value.scope,
        'defaultScope': value.defaultScope,
        'scopeApproval': value.scopeApproval,
    };
}

