/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
import type { AuditEntity } from './AuditEntity';
import { AuditEntityFromJSON, AuditEntityFromJSONTyped, AuditEntityToJSON, AuditEntityToJSONTyped } from './AuditEntity';
import type { Reference } from './Reference';
import { ReferenceFromJSON, ReferenceFromJSONTyped, ReferenceToJSON, ReferenceToJSONTyped } from './Reference';
import type { AuditOutcome } from './AuditOutcome';
import { AuditOutcomeFromJSON, AuditOutcomeFromJSONTyped, AuditOutcomeToJSON, AuditOutcomeToJSONTyped } from './AuditOutcome';
import type { AuditAccessPoint } from './AuditAccessPoint';
import {
  AuditAccessPointFromJSON,
  AuditAccessPointFromJSONTyped,
  AuditAccessPointToJSON,
  AuditAccessPointToJSONTyped,
} from './AuditAccessPoint';

/**
 *
 * @export
 * @interface Audit
 */
export interface Audit {
  /**
   *
   * @type {string}
   * @memberof Audit
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Audit
   */
  transactionId?: string;
  /**
   *
   * @type {string}
   * @memberof Audit
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof Audit
   */
  referenceType?: AuditReferenceTypeEnum;
  /**
   *
   * @type {string}
   * @memberof Audit
   */
  referenceId?: string;
  /**
   *
   * @type {AuditAccessPoint}
   * @memberof Audit
   */
  accessPoint?: AuditAccessPoint;
  /**
   *
   * @type {AuditEntity}
   * @memberof Audit
   */
  actor?: AuditEntity;
  /**
   *
   * @type {AuditEntity}
   * @memberof Audit
   */
  target?: AuditEntity;
  /**
   *
   * @type {AuditOutcome}
   * @memberof Audit
   */
  outcome?: AuditOutcome;
  /**
   *
   * @type {Date}
   * @memberof Audit
   */
  timestamp?: Date;
  /**
   *
   * @type {Reference}
   * @memberof Audit
   */
  reference?: Reference;
}

/**
 * @export
 */
export const AuditReferenceTypeEnum = {
  Platform: 'PLATFORM',
  Domain: 'DOMAIN',
  Application: 'APPLICATION',
  Organization: 'ORGANIZATION',
  Environment: 'ENVIRONMENT',
  ProtectedResource: 'PROTECTED_RESOURCE',
} as const;
export type AuditReferenceTypeEnum = typeof AuditReferenceTypeEnum[keyof typeof AuditReferenceTypeEnum];

/**
 * Check if a given object implements the Audit interface.
 */
export function instanceOfAudit(value: object): value is Audit {
  return true;
}

export function AuditFromJSON(json: any): Audit {
  return AuditFromJSONTyped(json, false);
}

export function AuditFromJSONTyped(json: any, ignoreDiscriminator: boolean): Audit {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    transactionId: json['transactionId'] == null ? undefined : json['transactionId'],
    type: json['type'] == null ? undefined : json['type'],
    referenceType: json['referenceType'] == null ? undefined : json['referenceType'],
    referenceId: json['referenceId'] == null ? undefined : json['referenceId'],
    accessPoint: json['accessPoint'] == null ? undefined : AuditAccessPointFromJSON(json['accessPoint']),
    actor: json['actor'] == null ? undefined : AuditEntityFromJSON(json['actor']),
    target: json['target'] == null ? undefined : AuditEntityFromJSON(json['target']),
    outcome: json['outcome'] == null ? undefined : AuditOutcomeFromJSON(json['outcome']),
    timestamp: json['timestamp'] == null ? undefined : new Date(json['timestamp']),
    reference: json['reference'] == null ? undefined : ReferenceFromJSON(json['reference']),
  };
}

export function AuditToJSON(json: any): Audit {
  return AuditToJSONTyped(json, false);
}

export function AuditToJSONTyped(value?: Audit | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    transactionId: value['transactionId'],
    type: value['type'],
    referenceType: value['referenceType'],
    referenceId: value['referenceId'],
    accessPoint: AuditAccessPointToJSON(value['accessPoint']),
    actor: AuditEntityToJSON(value['actor']),
    target: AuditEntityToJSON(value['target']),
    outcome: AuditOutcomeToJSON(value['outcome']),
    timestamp: value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    reference: ReferenceToJSON(value['reference']),
  };
}
