/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditsResource
 */
export interface AuditsResource {
    /**
     * 
     * @type {any}
     * @memberof AuditsResource
     */
    auditResource?: any;
}

export function AuditsResourceFromJSON(json: any): AuditsResource {
    return AuditsResourceFromJSONTyped(json, false);
}

export function AuditsResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditsResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auditResource': !exists(json, 'auditResource') ? undefined : json['auditResource'],
    };
}

export function AuditsResourceToJSON(value?: AuditsResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auditResource': value.auditResource,
    };
}

