/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CertificateSettings
 */
export interface CertificateSettings {
  /**
   *
   * @type {string}
   * @memberof CertificateSettings
   */
  fallbackCertificate?: string;
}

/**
 * Check if a given object implements the CertificateSettings interface.
 */
export function instanceOfCertificateSettings(value: object): value is CertificateSettings {
  return true;
}

export function CertificateSettingsFromJSON(json: any): CertificateSettings {
  return CertificateSettingsFromJSONTyped(json, false);
}

export function CertificateSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateSettings {
  if (json == null) {
    return json;
  }
  return {
    fallbackCertificate: json['fallbackCertificate'] == null ? undefined : json['fallbackCertificate'],
  };
}

export function CertificateSettingsToJSON(json: any): CertificateSettings {
  return CertificateSettingsToJSONTyped(json, false);
}

export function CertificateSettingsToJSONTyped(value?: CertificateSettings | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    fallbackCertificate: value['fallbackCertificate'],
  };
}
