/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificatesResource
 */
export interface CertificatesResource {
    /**
     * 
     * @type {any}
     * @memberof CertificatesResource
     */
    certificateResource?: any;
}

export function CertificatesResourceFromJSON(json: any): CertificatesResource {
    return CertificatesResourceFromJSONTyped(json, false);
}

export function CertificatesResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificatesResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'certificateResource': !exists(json, 'certificateResource') ? undefined : json['certificateResource'],
    };
}

export function CertificatesResourceToJSON(value?: CertificatesResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'certificateResource': value.certificateResource,
    };
}

