/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 * A resource server an application may request an ID-JAG for.
 * @export
 * @interface CrossAppAccessResourceServerEntity
 */
export interface CrossAppAccessResourceServerEntity {
  /**
   * Label the resource server is known by.
   * @type {string}
   * @memberof CrossAppAccessResourceServerEntity
   */
  name?: string;
  /**
   * Resource identifier of the resource server, carried by the "resource" claim.
   * @type {string}
   * @memberof CrossAppAccessResourceServerEntity
   */
  resource?: string;
  /**
   * Identifier of the resource server, stable across a rename.
   * @type {string}
   * @memberof CrossAppAccessResourceServerEntity
   */
  resourceServerId?: string;
  /**
   * Identifier of the trusted domain exposing this resource server.
   * @type {string}
   * @memberof CrossAppAccessResourceServerEntity
   */
  trustDomainId?: string;
  /**
   * Name of the trusted domain exposing this resource server.
   * @type {string}
   * @memberof CrossAppAccessResourceServerEntity
   */
  trustDomainName?: string;
}

/**
 * Check if a given object implements the CrossAppAccessResourceServerEntity interface.
 */
export function instanceOfCrossAppAccessResourceServerEntity(value: object): value is CrossAppAccessResourceServerEntity {
  return true;
}

export function CrossAppAccessResourceServerEntityFromJSON(json: any): CrossAppAccessResourceServerEntity {
  return CrossAppAccessResourceServerEntityFromJSONTyped(json, false);
}

export function CrossAppAccessResourceServerEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrossAppAccessResourceServerEntity {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    resource: json['resource'] == null ? undefined : json['resource'],
    resourceServerId: json['resourceServerId'] == null ? undefined : json['resourceServerId'],
    trustDomainId: json['trustDomainId'] == null ? undefined : json['trustDomainId'],
    trustDomainName: json['trustDomainName'] == null ? undefined : json['trustDomainName'],
  };
}

export function CrossAppAccessResourceServerEntityToJSON(json: any): CrossAppAccessResourceServerEntity {
  return CrossAppAccessResourceServerEntityToJSONTyped(json, false);
}

export function CrossAppAccessResourceServerEntityToJSONTyped(
  value?: CrossAppAccessResourceServerEntity | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    resource: value['resource'],
    resourceServerId: value['resourceServerId'],
    trustDomainId: value['trustDomainId'],
    trustDomainName: value['trustDomainName'],
  };
}
