/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeviceIdentifier
 */
export interface DeviceIdentifier {
  /**
   *
   * @type {string}
   * @memberof DeviceIdentifier
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof DeviceIdentifier
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof DeviceIdentifier
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof DeviceIdentifier
   */
  configuration?: string;
  /**
   *
   * @type {string}
   * @memberof DeviceIdentifier
   */
  referenceId?: string;
  /**
   *
   * @type {string}
   * @memberof DeviceIdentifier
   */
  referenceType?: DeviceIdentifierReferenceTypeEnum;
  /**
   *
   * @type {Date}
   * @memberof DeviceIdentifier
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof DeviceIdentifier
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const DeviceIdentifierReferenceTypeEnum = {
  Platform: 'PLATFORM',
  Domain: 'DOMAIN',
  Application: 'APPLICATION',
  Organization: 'ORGANIZATION',
  Environment: 'ENVIRONMENT',
  ProtectedResource: 'PROTECTED_RESOURCE',
} as const;
export type DeviceIdentifierReferenceTypeEnum = typeof DeviceIdentifierReferenceTypeEnum[keyof typeof DeviceIdentifierReferenceTypeEnum];

/**
 * Check if a given object implements the DeviceIdentifier interface.
 */
export function instanceOfDeviceIdentifier(value: object): value is DeviceIdentifier {
  return true;
}

export function DeviceIdentifierFromJSON(json: any): DeviceIdentifier {
  return DeviceIdentifierFromJSONTyped(json, false);
}

export function DeviceIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceIdentifier {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    type: json['type'] == null ? undefined : json['type'],
    configuration: json['configuration'] == null ? undefined : json['configuration'],
    referenceId: json['referenceId'] == null ? undefined : json['referenceId'],
    referenceType: json['referenceType'] == null ? undefined : json['referenceType'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  };
}

export function DeviceIdentifierToJSON(json: any): DeviceIdentifier {
  return DeviceIdentifierToJSONTyped(json, false);
}

export function DeviceIdentifierToJSONTyped(value?: DeviceIdentifier | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    type: value['type'],
    configuration: value['configuration'],
    referenceId: value['referenceId'],
    referenceType: value['referenceType'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
  };
}
