/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailValue
 */
export interface EmailValue {
    /**
     * 
     * @type {string}
     * @memberof EmailValue
     */
    email: string;
}

export function EmailValueFromJSON(json: any): EmailValue {
    return EmailValueFromJSONTyped(json, false);
}

export function EmailValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailValueToJSON(value?: EmailValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

