/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntrypointsResource
 */
export interface EntrypointsResource {
    /**
     * 
     * @type {any}
     * @memberof EntrypointsResource
     */
    entrypointResource?: any;
}

export function EntrypointsResourceFromJSON(json: any): EntrypointsResource {
    return EntrypointsResourceFromJSONTyped(json, false);
}

export function EntrypointsResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntrypointsResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entrypointResource': !exists(json, 'entrypointResource') ? undefined : json['entrypointResource'],
    };
}

export function EntrypointsResourceToJSON(value?: EntrypointsResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entrypointResource': value.entrypointResource,
    };
}

