/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Entrypoint
 */
export interface Entrypoint {
    /**
     * 
     * @type {string}
     * @memberof Entrypoint
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Entrypoint
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Entrypoint
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Entrypoint
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Entrypoint
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Entrypoint
     */
    organizationId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Entrypoint
     */
    defaultEntrypoint?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Entrypoint
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Entrypoint
     */
    updatedAt?: Date;
}

export function EntrypointFromJSON(json: any): Entrypoint {
    return EntrypointFromJSONTyped(json, false);
}

export function EntrypointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entrypoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'organizationId': !exists(json, 'organizationId') ? undefined : json['organizationId'],
        'defaultEntrypoint': !exists(json, 'defaultEntrypoint') ? undefined : json['defaultEntrypoint'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function EntrypointToJSON(value?: Entrypoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'url': value.url,
        'tags': value.tags,
        'organizationId': value.organizationId,
        'defaultEntrypoint': value.defaultEntrypoint,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

