/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
import type { JWK } from './JWK';
import { JWKFromJSON, JWKFromJSONTyped, JWKToJSON, JWKToJSONTyped } from './JWK';

/**
 *
 * @export
 * @interface JWKSet
 */
export interface JWKSet {
  /**
   *
   * @type {Array<JWK>}
   * @memberof JWKSet
   */
  keys?: Array<JWK>;
}

/**
 * Check if a given object implements the JWKSet interface.
 */
export function instanceOfJWKSet(value: object): value is JWKSet {
  return true;
}

export function JWKSetFromJSON(json: any): JWKSet {
  return JWKSetFromJSONTyped(json, false);
}

export function JWKSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): JWKSet {
  if (json == null) {
    return json;
  }
  return {
    keys: json['keys'] == null ? undefined : (json['keys'] as Array<any>).map(JWKFromJSON),
  };
}

export function JWKSetToJSON(json: any): JWKSet {
  return JWKSetToJSONTyped(json, false);
}

export function JWKSetToJSONTyped(value?: JWKSet | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    keys: value['keys'] == null ? undefined : (value['keys'] as Array<any>).map(JWKToJSON),
  };
}
