/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModifiedCertificateEntity
 */
export interface ModifiedCertificateEntity {
  /**
   *
   * @type {string}
   * @memberof ModifiedCertificateEntity
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ModifiedCertificateEntity
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ModifiedCertificateEntity
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof ModifiedCertificateEntity
   */
  configuration?: string;
  /**
   *
   * @type {string}
   * @memberof ModifiedCertificateEntity
   */
  domain?: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof ModifiedCertificateEntity
   */
  metadata?: { [key: string]: any };
  /**
   *
   * @type {Date}
   * @memberof ModifiedCertificateEntity
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ModifiedCertificateEntity
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ModifiedCertificateEntity
   */
  expiresAt?: Date;
  /**
   *
   * @type {boolean}
   * @memberof ModifiedCertificateEntity
   */
  system?: boolean;
}

/**
 * Check if a given object implements the ModifiedCertificateEntity interface.
 */
export function instanceOfModifiedCertificateEntity(value: object): value is ModifiedCertificateEntity {
  return true;
}

export function ModifiedCertificateEntityFromJSON(json: any): ModifiedCertificateEntity {
  return ModifiedCertificateEntityFromJSONTyped(json, false);
}

export function ModifiedCertificateEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifiedCertificateEntity {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    type: json['type'] == null ? undefined : json['type'],
    configuration: json['configuration'] == null ? undefined : json['configuration'],
    domain: json['domain'] == null ? undefined : json['domain'],
    metadata: json['metadata'] == null ? undefined : json['metadata'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
    expiresAt: json['expiresAt'] == null ? undefined : new Date(json['expiresAt']),
    system: json['system'] == null ? undefined : json['system'],
  };
}

export function ModifiedCertificateEntityToJSON(json: any): ModifiedCertificateEntity {
  return ModifiedCertificateEntityToJSONTyped(json, false);
}

export function ModifiedCertificateEntityToJSONTyped(value?: ModifiedCertificateEntity | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    type: value['type'],
    configuration: value['configuration'],
    domain: value['domain'],
    metadata: value['metadata'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    expiresAt: value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    system: value['system'],
  };
}
