/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NewOrganizationUser
 */
export interface NewOrganizationUser {
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  accountNonExpired?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  accountNonLocked?: boolean;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof NewOrganizationUser
   */
  additionalInformation?: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  client?: string;
  /**
   *
   * @type {Date}
   * @memberof NewOrganizationUser
   */
  createdAt?: Date;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  credentialsNonExpired?: boolean;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  domain?: string;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  email?: string;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  enabled?: boolean;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  externalId?: string;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  firstName?: string;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  forceResetPassword?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  internal?: boolean;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  lastName?: string;
  /**
   *
   * @type {Date}
   * @memberof NewOrganizationUser
   */
  lastPasswordReset?: Date;
  /**
   *
   * @type {Date}
   * @memberof NewOrganizationUser
   */
  loggedAt?: Date;
  /**
   *
   * @type {number}
   * @memberof NewOrganizationUser
   */
  loginsCount?: number;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  password?: string;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  preRegistration?: boolean;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  preferredLanguage?: string;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  registrationCompleted?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof NewOrganizationUser
   */
  serviceAccount?: boolean;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  source?: string;
  /**
   *
   * @type {Date}
   * @memberof NewOrganizationUser
   */
  updatedAt?: Date;
  /**
   *
   * @type {string}
   * @memberof NewOrganizationUser
   */
  username: string;
}

/**
 * Check if a given object implements the NewOrganizationUser interface.
 */
export function instanceOfNewOrganizationUser(value: object): value is NewOrganizationUser {
  if (!('username' in value) || value['username'] === undefined) return false;
  return true;
}

export function NewOrganizationUserFromJSON(json: any): NewOrganizationUser {
  return NewOrganizationUserFromJSONTyped(json, false);
}

export function NewOrganizationUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewOrganizationUser {
  if (json == null) {
    return json;
  }
  return {
    accountNonExpired: json['accountNonExpired'] == null ? undefined : json['accountNonExpired'],
    accountNonLocked: json['accountNonLocked'] == null ? undefined : json['accountNonLocked'],
    additionalInformation: json['additionalInformation'] == null ? undefined : json['additionalInformation'],
    client: json['client'] == null ? undefined : json['client'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    credentialsNonExpired: json['credentialsNonExpired'] == null ? undefined : json['credentialsNonExpired'],
    domain: json['domain'] == null ? undefined : json['domain'],
    email: json['email'] == null ? undefined : json['email'],
    enabled: json['enabled'] == null ? undefined : json['enabled'],
    externalId: json['externalId'] == null ? undefined : json['externalId'],
    firstName: json['firstName'] == null ? undefined : json['firstName'],
    forceResetPassword: json['forceResetPassword'] == null ? undefined : json['forceResetPassword'],
    internal: json['internal'] == null ? undefined : json['internal'],
    lastName: json['lastName'] == null ? undefined : json['lastName'],
    lastPasswordReset: json['lastPasswordReset'] == null ? undefined : new Date(json['lastPasswordReset']),
    loggedAt: json['loggedAt'] == null ? undefined : new Date(json['loggedAt']),
    loginsCount: json['loginsCount'] == null ? undefined : json['loginsCount'],
    password: json['password'] == null ? undefined : json['password'],
    preRegistration: json['preRegistration'] == null ? undefined : json['preRegistration'],
    preferredLanguage: json['preferredLanguage'] == null ? undefined : json['preferredLanguage'],
    registrationCompleted: json['registrationCompleted'] == null ? undefined : json['registrationCompleted'],
    serviceAccount: json['serviceAccount'] == null ? undefined : json['serviceAccount'],
    source: json['source'] == null ? undefined : json['source'],
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
    username: json['username'],
  };
}

export function NewOrganizationUserToJSON(json: any): NewOrganizationUser {
  return NewOrganizationUserToJSONTyped(json, false);
}

export function NewOrganizationUserToJSONTyped(value?: NewOrganizationUser | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    accountNonExpired: value['accountNonExpired'],
    accountNonLocked: value['accountNonLocked'],
    additionalInformation: value['additionalInformation'],
    client: value['client'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    credentialsNonExpired: value['credentialsNonExpired'],
    domain: value['domain'],
    email: value['email'],
    enabled: value['enabled'],
    externalId: value['externalId'],
    firstName: value['firstName'],
    forceResetPassword: value['forceResetPassword'],
    internal: value['internal'],
    lastName: value['lastName'],
    lastPasswordReset: value['lastPasswordReset'] == null ? value['lastPasswordReset'] : value['lastPasswordReset'].toISOString(),
    loggedAt: value['loggedAt'] == null ? value['loggedAt'] : value['loggedAt'].toISOString(),
    loginsCount: value['loginsCount'],
    password: value['password'],
    preRegistration: value['preRegistration'],
    preferredLanguage: value['preferredLanguage'],
    registrationCompleted: value['registrationCompleted'],
    serviceAccount: value['serviceAccount'],
    source: value['source'],
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    username: value['username'],
  };
}
