/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { exists, mapValues } from '../runtime';
import {
  NewProtectedResourceFeature,
  NewProtectedResourceFeatureFromJSON,
  NewProtectedResourceFeatureFromJSONTyped,
  NewProtectedResourceFeatureToJSON,
} from './NewProtectedResourceFeature';

/**
 *
 * @export
 * @interface NewProtectedResource
 */
export interface NewProtectedResource {
  /**
   *
   * @type {string}
   * @memberof NewProtectedResource
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof NewProtectedResource
   */
  description?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof NewProtectedResource
   */
  resourceIdentifiers: Array<string>;
  /**
   *
   * @type {string}
   * @memberof NewProtectedResource
   */
  clientId?: string;
  /**
   *
   * @type {string}
   * @memberof NewProtectedResource
   */
  clientSecret?: string;
  /**
   *
   * @type {string}
   * @memberof NewProtectedResource
   */
  type: string;
  /**
   *
   * @type {Array<NewProtectedResourceFeature>}
   * @memberof NewProtectedResource
   */
  features?: Array<NewProtectedResourceFeature>;
}

export function NewProtectedResourceFromJSON(json: any): NewProtectedResource {
  return NewProtectedResourceFromJSONTyped(json, false);
}

export function NewProtectedResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewProtectedResource {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    resourceIdentifiers: json['resourceIdentifiers'],
    clientId: !exists(json, 'clientId') ? undefined : json['clientId'],
    clientSecret: !exists(json, 'clientSecret') ? undefined : json['clientSecret'],
    type: json['type'],
    features: !exists(json, 'features') ? undefined : (json['features'] as Array<any>).map(NewProtectedResourceFeatureFromJSON),
  };
}

export function NewProtectedResourceToJSON(value?: NewProtectedResource | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    resourceIdentifiers: value.resourceIdentifiers,
    clientId: value.clientId,
    clientSecret: value.clientSecret,
    type: value.type,
    features: value.features === undefined ? undefined : (value.features as Array<any>).map(NewProtectedResourceFeatureToJSON),
  };
}
