/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import type { BulkCreateOrganizationUser } from './BulkCreateOrganizationUser';
import {
  instanceOfBulkCreateOrganizationUser,
  BulkCreateOrganizationUserFromJSON,
  BulkCreateOrganizationUserFromJSONTyped,
  BulkCreateOrganizationUserToJSON,
} from './BulkCreateOrganizationUser';
import type { BulkDeleteUser } from './BulkDeleteUser';
import { instanceOfBulkDeleteUser, BulkDeleteUserFromJSON, BulkDeleteUserFromJSONTyped, BulkDeleteUserToJSON } from './BulkDeleteUser';
import type { BulkUpdateUser } from './BulkUpdateUser';
import { instanceOfBulkUpdateUser, BulkUpdateUserFromJSON, BulkUpdateUserFromJSONTyped, BulkUpdateUserToJSON } from './BulkUpdateUser';

/**
 * @type OrganizationUserBulkRequest
 *
 * @export
 */
export type OrganizationUserBulkRequest =
  | ({ action: 'CREATE' } & BulkCreateOrganizationUser)
  | ({ action: 'DELETE' } & BulkDeleteUser)
  | ({ action: 'UPDATE' } & BulkUpdateUser);

export function OrganizationUserBulkRequestFromJSON(json: any): OrganizationUserBulkRequest {
  return OrganizationUserBulkRequestFromJSONTyped(json, false);
}

export function OrganizationUserBulkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserBulkRequest {
  if (json == null) {
    return json;
  }
  switch (json['action']) {
    case 'CREATE':
      return Object.assign({}, BulkCreateOrganizationUserFromJSONTyped(json, true), { action: 'CREATE' } as const);
    case 'DELETE':
      return Object.assign({}, BulkDeleteUserFromJSONTyped(json, true), { action: 'DELETE' } as const);
    case 'UPDATE':
      return Object.assign({}, BulkUpdateUserFromJSONTyped(json, true), { action: 'UPDATE' } as const);
    default:
      return json;
  }
}

export function OrganizationUserBulkRequestToJSON(json: any): any {
  return OrganizationUserBulkRequestToJSONTyped(json, false);
}

export function OrganizationUserBulkRequestToJSONTyped(
  value?: OrganizationUserBulkRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }
  switch (value['action']) {
    case 'CREATE':
      return Object.assign({}, BulkCreateOrganizationUserToJSON(value), { action: 'CREATE' } as const);
    case 'DELETE':
      return Object.assign({}, BulkDeleteUserToJSON(value), { action: 'DELETE' } as const);
    case 'UPDATE':
      return Object.assign({}, BulkUpdateUserToJSON(value), { action: 'UPDATE' } as const);
    default:
      return value;
  }
}
