/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchClientRegistrationSettings
 */
export interface PatchClientRegistrationSettings {
    /**
     * 
     * @type {boolean}
     * @memberof PatchClientRegistrationSettings
     */
    allowLocalhostRedirectUri?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchClientRegistrationSettings
     */
    allowHttpSchemeRedirectUri?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchClientRegistrationSettings
     */
    allowWildCardRedirectUri?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchClientRegistrationSettings
     */
    defaultScopes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchClientRegistrationSettings
     */
    allowedScopes?: Array<string>;
}

export function PatchClientRegistrationSettingsFromJSON(json: any): PatchClientRegistrationSettings {
    return PatchClientRegistrationSettingsFromJSONTyped(json, false);
}

export function PatchClientRegistrationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchClientRegistrationSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'allowLocalhostRedirectUri': !exists(json, 'allowLocalhostRedirectUri') ? undefined : json['allowLocalhostRedirectUri'],
        'allowHttpSchemeRedirectUri': !exists(json, 'allowHttpSchemeRedirectUri') ? undefined : json['allowHttpSchemeRedirectUri'],
        'allowWildCardRedirectUri': !exists(json, 'allowWildCardRedirectUri') ? undefined : json['allowWildCardRedirectUri'],
        'defaultScopes': !exists(json, 'defaultScopes') ? undefined : json['defaultScopes'],
        'allowedScopes': !exists(json, 'allowedScopes') ? undefined : json['allowedScopes'],
    };
}

export function PatchClientRegistrationSettingsToJSON(value?: PatchClientRegistrationSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'allowLocalhostRedirectUri': value.allowLocalhostRedirectUri,
        'allowHttpSchemeRedirectUri': value.allowHttpSchemeRedirectUri,
        'allowWildCardRedirectUri': value.allowWildCardRedirectUri,
        'defaultScopes': value.defaultScopes,
        'allowedScopes': value.allowedScopes,
    };
}

