/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PatchSAMLSettings
 */
export interface PatchSAMLSettings {
  /**
   *
   * @type {boolean}
   * @memberof PatchSAMLSettings
   */
  enabled?: boolean;
  /**
   *
   * @type {string}
   * @memberof PatchSAMLSettings
   */
  entityId?: string;
  /**
   *
   * @type {string}
   * @memberof PatchSAMLSettings
   */
  certificate?: string;
  /**
   *
   * @type {Set<string>}
   * @memberof PatchSAMLSettings
   */
  requiredPermissions?: Set<PatchSAMLSettingsRequiredPermissionsEnum>;
}

/**
 * @export
 */
export const PatchSAMLSettingsRequiredPermissionsEnum = {
  Organization: 'ORGANIZATION',
  OrganizationSettings: 'ORGANIZATION_SETTINGS',
  OrganizationIdentityProvider: 'ORGANIZATION_IDENTITY_PROVIDER',
  OrganizationAudit: 'ORGANIZATION_AUDIT',
  OrganizationReporter: 'ORGANIZATION_REPORTER',
  OrganizationScope: 'ORGANIZATION_SCOPE',
  OrganizationUser: 'ORGANIZATION_USER',
  OrganizationGroup: 'ORGANIZATION_GROUP',
  OrganizationRole: 'ORGANIZATION_ROLE',
  OrganizationTag: 'ORGANIZATION_TAG',
  OrganizationEntrypoint: 'ORGANIZATION_ENTRYPOINT',
  OrganizationForm: 'ORGANIZATION_FORM',
  OrganizationMember: 'ORGANIZATION_MEMBER',
  Environment: 'ENVIRONMENT',
  DataPlane: 'DATA_PLANE',
  Domain: 'DOMAIN',
  DomainSettings: 'DOMAIN_SETTINGS',
  DomainForm: 'DOMAIN_FORM',
  DomainEmailTemplate: 'DOMAIN_EMAIL_TEMPLATE',
  DomainExtensionPoint: 'DOMAIN_EXTENSION_POINT',
  DomainIdentityProvider: 'DOMAIN_IDENTITY_PROVIDER',
  DomainAuthorizationEngine: 'DOMAIN_AUTHORIZATION_ENGINE',
  DomainAudit: 'DOMAIN_AUDIT',
  DomainCertificate: 'DOMAIN_CERTIFICATE',
  DomainUser: 'DOMAIN_USER',
  DomainUserDevice: 'DOMAIN_USER_DEVICE',
  DomainGroup: 'DOMAIN_GROUP',
  DomainRole: 'DOMAIN_ROLE',
  DomainScim: 'DOMAIN_SCIM',
  DomainScope: 'DOMAIN_SCOPE',
  DomainExtensionGrant: 'DOMAIN_EXTENSION_GRANT',
  DomainOpenid: 'DOMAIN_OPENID',
  DomainSaml: 'DOMAIN_SAML',
  DomainUma: 'DOMAIN_UMA',
  DomainUmaScope: 'DOMAIN_UMA_SCOPE',
  DomainReporter: 'DOMAIN_REPORTER',
  DomainMember: 'DOMAIN_MEMBER',
  DomainAnalytics: 'DOMAIN_ANALYTICS',
  DomainFactor: 'DOMAIN_FACTOR',
  DomainResource: 'DOMAIN_RESOURCE',
  DomainFlow: 'DOMAIN_FLOW',
  DomainAlert: 'DOMAIN_ALERT',
  DomainAlertNotifier: 'DOMAIN_ALERT_NOTIFIER',
  DomainBotDetection: 'DOMAIN_BOT_DETECTION',
  DomainDeviceIdentifier: 'DOMAIN_DEVICE_IDENTIFIER',
  DomainAuthdeviceNotifier: 'DOMAIN_AUTHDEVICE_NOTIFIER',
  DomainI18NDictionary: 'DOMAIN_I18N_DICTIONARY',
  DomainTheme: 'DOMAIN_THEME',
  Application: 'APPLICATION',
  ApplicationSettings: 'APPLICATION_SETTINGS',
  ApplicationIdentityProvider: 'APPLICATION_IDENTITY_PROVIDER',
  ApplicationForm: 'APPLICATION_FORM',
  ApplicationEmailTemplate: 'APPLICATION_EMAIL_TEMPLATE',
  ApplicationOpenid: 'APPLICATION_OPENID',
  ApplicationSaml: 'APPLICATION_SAML',
  ApplicationCertificate: 'APPLICATION_CERTIFICATE',
  ApplicationMember: 'APPLICATION_MEMBER',
  ApplicationFactor: 'APPLICATION_FACTOR',
  ApplicationResource: 'APPLICATION_RESOURCE',
  ApplicationAnalytics: 'APPLICATION_ANALYTICS',
  ApplicationFlow: 'APPLICATION_FLOW',
  ProtectedResource: 'PROTECTED_RESOURCE',
  LicenseNotification: 'LICENSE_NOTIFICATION',
  Installation: 'INSTALLATION',
} as const;
export type PatchSAMLSettingsRequiredPermissionsEnum =
  typeof PatchSAMLSettingsRequiredPermissionsEnum[keyof typeof PatchSAMLSettingsRequiredPermissionsEnum];

/**
 * Check if a given object implements the PatchSAMLSettings interface.
 */
export function instanceOfPatchSAMLSettings(value: object): value is PatchSAMLSettings {
  return true;
}

export function PatchSAMLSettingsFromJSON(json: any): PatchSAMLSettings {
  return PatchSAMLSettingsFromJSONTyped(json, false);
}

export function PatchSAMLSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchSAMLSettings {
  if (json == null) {
    return json;
  }
  return {
    enabled: json['enabled'] == null ? undefined : json['enabled'],
    entityId: json['entityId'] == null ? undefined : json['entityId'],
    certificate: json['certificate'] == null ? undefined : json['certificate'],
    requiredPermissions: json['requiredPermissions'] == null ? undefined : new Set(json['requiredPermissions']),
  };
}

export function PatchSAMLSettingsToJSON(json: any): PatchSAMLSettings {
  return PatchSAMLSettingsToJSONTyped(json, false);
}

export function PatchSAMLSettingsToJSONTyped(value?: PatchSAMLSettings | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    enabled: value['enabled'],
    entityId: value['entityId'],
    certificate: value['certificate'],
    requiredPermissions: value['requiredPermissions'] == null ? undefined : Array.from(value['requiredPermissions'] as Set<any>),
  };
}
