/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreviewResponse
 */
export interface PreviewResponse {
    /**
     * 
     * @type {string}
     * @memberof PreviewResponse
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof PreviewResponse
     */
    type?: PreviewResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PreviewResponse
     */
    template?: string;
}


/**
 * @export
 */
export const PreviewResponseTypeEnum = {
    Email: 'EMAIL',
    Form: 'FORM'
} as const;
export type PreviewResponseTypeEnum = typeof PreviewResponseTypeEnum[keyof typeof PreviewResponseTypeEnum];


export function PreviewResponseFromJSON(json: any): PreviewResponse {
    return PreviewResponseFromJSONTyped(json, false);
}

export function PreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : json['content'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'template': !exists(json, 'template') ? undefined : json['template'],
    };
}

export function PreviewResponseToJSON(value?: PreviewResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'type': value.type,
        'template': value.template,
    };
}

