/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
import type { AssessmentSettings } from './AssessmentSettings';
import {
  AssessmentSettingsFromJSON,
  AssessmentSettingsFromJSONTyped,
  AssessmentSettingsToJSON,
  AssessmentSettingsToJSONTyped,
} from './AssessmentSettings';

/**
 *
 * @export
 * @interface RiskAssessmentSettings
 */
export interface RiskAssessmentSettings {
  /**
   *
   * @type {AssessmentSettings}
   * @memberof RiskAssessmentSettings
   */
  deviceAssessment?: AssessmentSettings;
  /**
   *
   * @type {boolean}
   * @memberof RiskAssessmentSettings
   */
  enabled?: boolean;
  /**
   *
   * @type {AssessmentSettings}
   * @memberof RiskAssessmentSettings
   */
  geoVelocityAssessment?: AssessmentSettings;
  /**
   *
   * @type {AssessmentSettings}
   * @memberof RiskAssessmentSettings
   */
  ipReputationAssessment?: AssessmentSettings;
}

/**
 * Check if a given object implements the RiskAssessmentSettings interface.
 */
export function instanceOfRiskAssessmentSettings(value: object): value is RiskAssessmentSettings {
  return true;
}

export function RiskAssessmentSettingsFromJSON(json: any): RiskAssessmentSettings {
  return RiskAssessmentSettingsFromJSONTyped(json, false);
}

export function RiskAssessmentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAssessmentSettings {
  if (json == null) {
    return json;
  }
  return {
    deviceAssessment: json['deviceAssessment'] == null ? undefined : AssessmentSettingsFromJSON(json['deviceAssessment']),
    enabled: json['enabled'] == null ? undefined : json['enabled'],
    geoVelocityAssessment: json['geoVelocityAssessment'] == null ? undefined : AssessmentSettingsFromJSON(json['geoVelocityAssessment']),
    ipReputationAssessment: json['ipReputationAssessment'] == null ? undefined : AssessmentSettingsFromJSON(json['ipReputationAssessment']),
  };
}

export function RiskAssessmentSettingsToJSON(json: any): RiskAssessmentSettings {
  return RiskAssessmentSettingsToJSONTyped(json, false);
}

export function RiskAssessmentSettingsToJSONTyped(value?: RiskAssessmentSettings | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    deviceAssessment: AssessmentSettingsToJSON(value['deviceAssessment']),
    enabled: value['enabled'],
    geoVelocityAssessment: AssessmentSettingsToJSON(value['geoVelocityAssessment']),
    ipReputationAssessment: AssessmentSettingsToJSON(value['ipReputationAssessment']),
  };
}
