/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Role
 */
export interface Role {
  /**
   *
   * @type {string}
   * @memberof Role
   */
  assignableType?: RoleAssignableTypeEnum;
  /**
   *
   * @type {Date}
   * @memberof Role
   */
  createdAt?: Date;
  /**
   *
   * @type {boolean}
   * @memberof Role
   */
  defaultRole?: boolean;
  /**
   *
   * @type {string}
   * @memberof Role
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof Role
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof Role
   */
  internalOnly?: boolean;
  /**
   *
   * @type {string}
   * @memberof Role
   */
  name?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Role
   */
  oauthScopes?: Array<string>;
  /**
   *
   * @type {{ [key: string]: Set<string>; }}
   * @memberof Role
   */
  permissionAcls?: { [key: string]: Set<InnerEnum> };
  /**
   *
   * @type {string}
   * @memberof Role
   */
  referenceId?: string;
  /**
   *
   * @type {string}
   * @memberof Role
   */
  referenceType?: RoleReferenceTypeEnum;
  /**
   *
   * @type {boolean}
   * @memberof Role
   */
  system?: boolean;
  /**
   *
   * @type {Date}
   * @memberof Role
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const RoleAssignableTypeEnum = {
  Platform: 'PLATFORM',
  Domain: 'DOMAIN',
  Application: 'APPLICATION',
  Organization: 'ORGANIZATION',
  Environment: 'ENVIRONMENT',
  ProtectedResource: 'PROTECTED_RESOURCE',
} as const;
export type RoleAssignableTypeEnum = typeof RoleAssignableTypeEnum[keyof typeof RoleAssignableTypeEnum];

/**
 * @export
 */
export const RolePermissionAclsEnum = {
  Create: 'CREATE',
  Read: 'READ',
  List: 'LIST',
  Update: 'UPDATE',
  Delete: 'DELETE',
} as const;
export type RolePermissionAclsEnum = typeof RolePermissionAclsEnum[keyof typeof RolePermissionAclsEnum];

/**
 * @export
 */
export const RoleReferenceTypeEnum = {
  Platform: 'PLATFORM',
  Domain: 'DOMAIN',
  Application: 'APPLICATION',
  Organization: 'ORGANIZATION',
  Environment: 'ENVIRONMENT',
  ProtectedResource: 'PROTECTED_RESOURCE',
} as const;
export type RoleReferenceTypeEnum = typeof RoleReferenceTypeEnum[keyof typeof RoleReferenceTypeEnum];

/**
 * Check if a given object implements the Role interface.
 */
export function instanceOfRole(value: object): value is Role {
  return true;
}

export function RoleFromJSON(json: any): Role {
  return RoleFromJSONTyped(json, false);
}

export function RoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role {
  if (json == null) {
    return json;
  }
  return {
    assignableType: json['assignableType'] == null ? undefined : json['assignableType'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    defaultRole: json['defaultRole'] == null ? undefined : json['defaultRole'],
    description: json['description'] == null ? undefined : json['description'],
    id: json['id'] == null ? undefined : json['id'],
    internalOnly: json['internalOnly'] == null ? undefined : json['internalOnly'],
    name: json['name'] == null ? undefined : json['name'],
    oauthScopes: json['oauthScopes'] == null ? undefined : json['oauthScopes'],
    permissionAcls: json['permissionAcls'] == null ? undefined : json['permissionAcls'],
    referenceId: json['referenceId'] == null ? undefined : json['referenceId'],
    referenceType: json['referenceType'] == null ? undefined : json['referenceType'],
    system: json['system'] == null ? undefined : json['system'],
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  };
}

export function RoleToJSON(json: any): Role {
  return RoleToJSONTyped(json, false);
}

export function RoleToJSONTyped(value?: Role | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    assignableType: value['assignableType'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    defaultRole: value['defaultRole'],
    description: value['description'],
    id: value['id'],
    internalOnly: value['internalOnly'],
    name: value['name'],
    oauthScopes: value['oauthScopes'],
    permissionAcls: value['permissionAcls'],
    referenceId: value['referenceId'],
    referenceType: value['referenceType'],
    system: value['system'],
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
  };
}
