/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { mapValues } from '../runtime';
import type { ScopeEntity } from './ScopeEntity';
import { ScopeEntityFromJSON, ScopeEntityFromJSONTyped, ScopeEntityToJSON, ScopeEntityToJSONTyped } from './ScopeEntity';
import type { ApplicationEntity } from './ApplicationEntity';
import {
  ApplicationEntityFromJSON,
  ApplicationEntityFromJSONTyped,
  ApplicationEntityToJSON,
  ApplicationEntityToJSONTyped,
} from './ApplicationEntity';
import type { UserId } from './UserId';
import { UserIdFromJSON, UserIdFromJSONTyped, UserIdToJSON, UserIdToJSONTyped } from './UserId';

/**
 *
 * @export
 * @interface ScopeApprovalEntity
 */
export interface ScopeApprovalEntity {
  /**
   *
   * @type {ApplicationEntity}
   * @memberof ScopeApprovalEntity
   */
  clientEntity?: ApplicationEntity;
  /**
   *
   * @type {string}
   * @memberof ScopeApprovalEntity
   */
  clientId?: string;
  /**
   *
   * @type {Date}
   * @memberof ScopeApprovalEntity
   */
  createdAt?: Date;
  /**
   *
   * @type {string}
   * @memberof ScopeApprovalEntity
   */
  domain?: string;
  /**
   *
   * @type {Date}
   * @memberof ScopeApprovalEntity
   */
  expiresAt?: Date;
  /**
   *
   * @type {string}
   * @memberof ScopeApprovalEntity
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ScopeApprovalEntity
   */
  scope?: string;
  /**
   *
   * @type {ScopeEntity}
   * @memberof ScopeApprovalEntity
   */
  scopeEntity?: ScopeEntity;
  /**
   *
   * @type {string}
   * @memberof ScopeApprovalEntity
   */
  status?: ScopeApprovalEntityStatusEnum;
  /**
   *
   * @type {string}
   * @memberof ScopeApprovalEntity
   */
  transactionId?: string;
  /**
   *
   * @type {Date}
   * @memberof ScopeApprovalEntity
   */
  updatedAt?: Date;
  /**
   *
   * @type {UserId}
   * @memberof ScopeApprovalEntity
   */
  userId?: UserId;
}

/**
 * @export
 */
export const ScopeApprovalEntityStatusEnum = {
  Approved: 'APPROVED',
  Denied: 'DENIED',
} as const;
export type ScopeApprovalEntityStatusEnum = typeof ScopeApprovalEntityStatusEnum[keyof typeof ScopeApprovalEntityStatusEnum];

/**
 * Check if a given object implements the ScopeApprovalEntity interface.
 */
export function instanceOfScopeApprovalEntity(value: object): value is ScopeApprovalEntity {
  return true;
}

export function ScopeApprovalEntityFromJSON(json: any): ScopeApprovalEntity {
  return ScopeApprovalEntityFromJSONTyped(json, false);
}

export function ScopeApprovalEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScopeApprovalEntity {
  if (json == null) {
    return json;
  }
  return {
    clientEntity: json['clientEntity'] == null ? undefined : ApplicationEntityFromJSON(json['clientEntity']),
    clientId: json['clientId'] == null ? undefined : json['clientId'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    domain: json['domain'] == null ? undefined : json['domain'],
    expiresAt: json['expiresAt'] == null ? undefined : new Date(json['expiresAt']),
    id: json['id'] == null ? undefined : json['id'],
    scope: json['scope'] == null ? undefined : json['scope'],
    scopeEntity: json['scopeEntity'] == null ? undefined : ScopeEntityFromJSON(json['scopeEntity']),
    status: json['status'] == null ? undefined : json['status'],
    transactionId: json['transactionId'] == null ? undefined : json['transactionId'],
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
    userId: json['userId'] == null ? undefined : UserIdFromJSON(json['userId']),
  };
}

export function ScopeApprovalEntityToJSON(json: any): ScopeApprovalEntity {
  return ScopeApprovalEntityToJSONTyped(json, false);
}

export function ScopeApprovalEntityToJSONTyped(value?: ScopeApprovalEntity | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    clientEntity: ApplicationEntityToJSON(value['clientEntity']),
    clientId: value['clientId'],
    createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    domain: value['domain'],
    expiresAt: value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    id: value['id'],
    scope: value['scope'],
    scopeEntity: ScopeEntityToJSON(value['scopeEntity']),
    status: value['status'],
    transactionId: value['transactionId'],
    updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    userId: UserIdToJSON(value['userId']),
  };
}
