/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ServiceResource
 */
export interface ServiceResource {
  /**
   *
   * @type {string}
   * @memberof ServiceResource
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ServiceResource
   */
  referenceType?: ServiceResourceReferenceTypeEnum;
  /**
   *
   * @type {string}
   * @memberof ServiceResource
   */
  referenceId?: string;
  /**
   *
   * @type {string}
   * @memberof ServiceResource
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ServiceResource
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof ServiceResource
   */
  configuration?: string;
  /**
   *
   * @type {Date}
   * @memberof ServiceResource
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ServiceResource
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const ServiceResourceReferenceTypeEnum = {
  Platform: 'PLATFORM',
  Domain: 'DOMAIN',
  Application: 'APPLICATION',
  Organization: 'ORGANIZATION',
  Environment: 'ENVIRONMENT',
} as const;
export type ServiceResourceReferenceTypeEnum = typeof ServiceResourceReferenceTypeEnum[keyof typeof ServiceResourceReferenceTypeEnum];

export function ServiceResourceFromJSON(json: any): ServiceResource {
  return ServiceResourceFromJSONTyped(json, false);
}

export function ServiceResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResource {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    referenceType: !exists(json, 'referenceType') ? undefined : json['referenceType'],
    referenceId: !exists(json, 'referenceId') ? undefined : json['referenceId'],
    name: !exists(json, 'name') ? undefined : json['name'],
    type: !exists(json, 'type') ? undefined : json['type'],
    configuration: !exists(json, 'configuration') ? undefined : json['configuration'],
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
  };
}

export function ServiceResourceToJSON(value?: ServiceResource | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    referenceType: value.referenceType,
    referenceId: value.referenceId,
    name: value.name,
    type: value.type,
    configuration: value.configuration,
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
  };
}
