/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceResource
 */
export interface ServiceResource {
    /**
     * 
     * @type {string}
     * @memberof ServiceResource
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResource
     */
    referenceType?: ServiceResourceReferenceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceResource
     */
    referenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResource
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResource
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResource
     */
    configuration?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceResource
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceResource
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const ServiceResourceReferenceTypeEnum = {
    Platform: 'PLATFORM',
    Domain: 'DOMAIN',
    Application: 'APPLICATION',
    Organization: 'ORGANIZATION',
    Environment: 'ENVIRONMENT'
} as const;
export type ServiceResourceReferenceTypeEnum = typeof ServiceResourceReferenceTypeEnum[keyof typeof ServiceResourceReferenceTypeEnum];


export function ServiceResourceFromJSON(json: any): ServiceResource {
    return ServiceResourceFromJSONTyped(json, false);
}

export function ServiceResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'referenceType': !exists(json, 'referenceType') ? undefined : json['referenceType'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'configuration': !exists(json, 'configuration') ? undefined : json['configuration'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ServiceResourceToJSON(value?: ServiceResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'referenceType': value.referenceType,
        'referenceId': value.referenceId,
        'name': value.name,
        'type': value.type,
        'configuration': value.configuration,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

