/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateI18nDictionary
 */
export interface UpdateI18nDictionary {
    /**
     * 
     * @type {string}
     * @memberof UpdateI18nDictionary
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateI18nDictionary
     */
    locale?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UpdateI18nDictionary
     */
    entries?: { [key: string]: string; };
}

export function UpdateI18nDictionaryFromJSON(json: any): UpdateI18nDictionary {
    return UpdateI18nDictionaryFromJSONTyped(json, false);
}

export function UpdateI18nDictionaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateI18nDictionary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'entries': !exists(json, 'entries') ? undefined : json['entries'],
    };
}

export function UpdateI18nDictionaryToJSON(value?: UpdateI18nDictionary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'locale': value.locale,
        'entries': value.entries,
    };
}

