/* tslint:disable */
/* eslint-disable */
/**
 * Gravitee.io - Access Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConsentsResource
 */
export interface UserConsentsResource {
    /**
     * 
     * @type {any}
     * @memberof UserConsentsResource
     */
    userConsentResource?: any;
}

export function UserConsentsResourceFromJSON(json: any): UserConsentsResource {
    return UserConsentsResourceFromJSONTyped(json, false);
}

export function UserConsentsResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConsentsResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userConsentResource': !exists(json, 'userConsentResource') ? undefined : json['userConsentResource'],
    };
}

export function UserConsentsResourceToJSON(value?: UserConsentsResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userConsentResource': value.userConsentResource,
    };
}

