databaseChangeLog:
  - changeSet:
      id: 3.5.2
      author: GraviteeSource Team
      changes:

        # Credentials
        ##############
        - addColumn:
            tableName: webauthn_credentials
            columns:
              - column: {name: aaguid, type: nvarchar(64), constraints: { nullable: true } }
              - column: {name: att_stmt_fmt, type: nvarchar(64), constraints: { nullable: true } }
              - column: {name: att_stmt, type: clob, constraints: { nullable: true } }

        # Domains
        ###############
        - renameColumn:
            tableName: domain_vhosts
            columnDataType: boolean
            oldColumnName: override_endpoints
            newColumnName: override_entrypoint
