= Release process

== 📝 Description

This repo contains some https://github.com/google/zx[zx] scripts to execute the different release steps for AM.

It will allow you to run these pipeline on CircleCI to:

* Launch git release and maven artifact deployment to our local artifactory
* Launch deploy maven artifact to maven central (sonatype)
* Launch the build and publish of docker images
* Launch the build and publish the RPM of AM
* Launch the helm release and publish
* Launch the changelog generation (open a PR pre-filled)

== 🛠 Requirement

To run the scripts, you need to have:

* Node.js >= 16.0.0 (configured in link:.nvmrc[.nvmrc] with v18.4.0)
* (optional) https://github.com/google/zx[zx], to install it you just have to run:
+
[source,shell]
----
npm i -g zx
# Check everything is ok:
zx -v
----

* Get your own CircleCI token to be able to trigger build
** Go to https://app.circleci.com/settings/user/tokens, create a token and copy it. It is your personal token on CircleCI
** You can create an `.env` file with your key on `CIRCLECI_TOKEN` variable. We use https://github.com/motdotla/dotenv#readme[dotenv] read it. The following command in the `release` folder will create a `.env` file with the token:
+
[source,shell]
----
touch .env && echo "CIRCLECI_TOKEN=[YOUR_TOKEN]" > .env
----
** Or you can just export this variable (maybe add it in your `.bashrc` / `.zshrc`)
+
[source,shell]
----
export CIRCLECI_TOKEN="[YOUR_TOKEN]"
----

* The scripts need some dependencies, you can install them from the `release` folder with:
+
[source, shell]
----
npm install
----

== 🏁 Run release alpha version pipeline[[run_release_alpha_version_pipeline]]

Lunch only required steps in one CircleCI pipeline to release an alpha version. There are two methods available:

* npm run
[source, shell]
----
npm run am-release -- \
  --branch 4.3.x --gio-version 4.3.3-alpha.1 \
  --dry-run \
  release-alpha-version
----
* curl HTTP
[source, shell]
----
curl --location --request POST 'https://circleci.com/api/v2/project/gh/gravitee-io/gravitee-access-management/pipeline' \
--header 'Content-Type: application/json' \
--header "Circle-Token: $CIRCLECI_TOKEN" \
--data-raw '{
    "branch": "4.3.x",
    "parameters": {
        "gio_action": "release-alpha-version",
        "dry_run": true,
        "rc_requested": true,
        "graviteeio_version": "4.3.3-alpha.1",
        "run-container-test": false
    }
}'
----

== 🏁 Run release version pipeline[[run_release_version_pipeline]]

Lunch all steps in one CircleCI pipeline to release a new version. There are two methods available:

* npm run
[source, shell]
----
npm run am-release -- \
  --branch master --gio-version 4.4.0 \
  --dry-run \
  release-version
----

* curl HTTP
[source, shell]
----
curl --location --request POST 'https://circleci.com/api/v2/project/gh/gravitee-io/gravitee-access-management/pipeline' \
--header 'Content-Type: application/json' \
--header "Circle-Token: $CIRCLECI_TOKEN" \
--data-raw '{
    "branch": "master",
    "parameters": {
        "gio_action": "release-version",
        "dry_run": true,
        "rc_requested": false,
        "graviteeio_version": "4.4.0",
        "run-container-test": false,
        "tag_latest": false,
        "tag_latest_support": true
    }
}'
----

== 🏁 Run a single job[[Usage]]

WARNING: Running single job is an old way of release. Please follow <<run_release_alpha_version_pipeline, Run release alpha version pipeline>> or <<run_release_version_pipeline, Run release version pipeline>> for releasing AM.

Thanks to link:package.json[package.json], you can run those scripts as simple `npm` commands (do not forget to use `npm i` before starting).

Each of the commands needs a `CIRCLECI_TOKEN`.

You can see help and example by running:

[source, shell]
----
npm run am-release -- help
----

Examples:

* Run the git release in dry run:
+
[source, shell]
----
npm run am-release -- --branch master --gio-version 4.3.0 --dry-run release-git
----

* Run all release step:
+
[source, shell]
----
npm run am-release -- \
  --branch master --gio-version 4.3.0 \
  --dry-run \
  release-git

npm run am-release -- \
  --branch master --gio-version 4.3.0 \
  --dry-run \
  publish-maven-central

npm run am-release -- \
  --branch master --gio-version 4.3.0 \
  --dry-run \
  publish-docker-images \
  --tag-latest --no-tag-latest-support

npm run am-release -- \
  --branch master --gio-version 4.3.0 \
  --dry-run \
  publish-rpms

npm run am-release -- \
  --branch master --gio-version 4.3.0 \
  --dry-run \
  release-helm

npm run am-release -- \
  --branch master --gio-version 4.3.0 \
  --dry-run \
  release-notes
----


== 💡 Functional overview

This is the functional dependencies between each step:

[mermaid]
----
flowchart LR
    A[release-git]
    A -->B[publish-maven-central]
    A -->C[publish-docker-images]
    A -->D[publish-rpms]
    A -->E[release-helm]
    A -->F[release-notes]
----

Note that the configuration of CircleCI *disallow* multiple build on the same branch (a new build cancel the previous one). It means that we have to run one step at a time.

== 🏁 Hotfix release

This option is to release hotfix of specific version. To do this follow the command below:


[source, shell]
----
npm run am-release -- \
  --branch 4.3.4 --gio-version 4.3.4-hotfix.1 \
  --dry-run \
  release-hotfix
----
