id=policy-example-user-action
name=Example User Action
version=${project.version}
description=Example User Action Policy - demonstrates extension of AbstractUserActionPolicy
class=io.gravitee.am.policy.user.action.example.ExampleUserActionPolicy
type=policy