#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM alpine:3.22 AS build-env
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEAM_VERSION=0

RUN apk update \
    && apk add --update --no-cache unzip \
    && rm -rf /var/cache/apk/*

ADD ./gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip /tmp/

RUN unzip /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip -d /gravitee-tmp/ \
    && chmod -R g=u /gravitee-tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}/ \
    && rm -rf /tmp/*

FROM eclipse-temurin:21.0.9_10-jre-noble AS build-jattach
LABEL maintainer="contact@graviteesource.com"

ARG JATTACH_VERSION=2.2

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential wget ca-certificates && \
    wget -O /tmp/jattach.tar.gz https://github.com/apangin/jattach/archive/refs/tags/v${JATTACH_VERSION}.tar.gz && \
    tar -xf /tmp/jattach.tar.gz -C /tmp/ && \
    make -C /tmp/jattach-${JATTACH_VERSION} && \
    JATTACH_SRC="/tmp/jattach-${JATTACH_VERSION}/jattach" && \
    if [ ! -f "${JATTACH_SRC}" ]; then \
        JATTACH_SRC="/tmp/jattach-${JATTACH_VERSION}/build/jattach"; \
    fi && \
    install -m 0755 "${JATTACH_SRC}" /usr/local/bin/jattach && \
    apt-get purge -y build-essential wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/jattach-${JATTACH_VERSION} /tmp/jattach.tar.gz

FROM eclipse-temurin:21.0.9_10-jre-noble
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEAM_VERSION=0
ENV GRAVITEE_AM_HOME=/opt/graviteeio-am-management-api

# Upgrade libc6
USER root
RUN apt-get update && \
    apt-get upgrade -y libc6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends libjemalloc2 ca-certificates && \
    JEMALLOC_PATH=$(dpkg -L libjemalloc2 | grep -E '/lib.*/libjemalloc\.so\.2$' | head -1) && \
    ln -sf "${JEMALLOC_PATH}" /usr/lib/libjemalloc.so.2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LD_PRELOAD=/usr/lib/libjemalloc.so.2

RUN groupmod --new-name graviteeio ubuntu && \
 adduser --disabled-password --no-create-home -uid 1001 graviteeio --ingroup graviteeio

COPY --from=build-env --chown=1001:1000 /gravitee-tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}/ ${GRAVITEE_AM_HOME}/
COPY --from=build-jattach /usr/local/bin/jattach /usr/local/bin/jattach

RUN chmod -R g=u ${GRAVITEE_AM_HOME}

WORKDIR ${GRAVITEE_AM_HOME}

EXPOSE 8093

VOLUME ["/opt/graviteeio-am-management-api/logs"]

CMD ["./bin/gravitee"]

USER graviteeio
