#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM graviteeio/java:8
MAINTAINER Gravitee Team <http://gravitee.io>

ARG GRAVITEEAM_VERSION=0
ENV GRAVITEEAM_HOME /opt/graviteeio-am-management-api

# Update to get support for Zip/Unzip, nc and wget
RUN apk add --update zip unzip netcat-openbsd wget

RUN wget --no-check-certificate -O /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip https://oss.sonatype.org/service/local/artifact/maven/content\?r\=snapshots\&g\=io.gravitee.am.management.standalone\&a\=gravitee-am-management-api-standalone-distribution-zip\&p\=zip\&v\=${GRAVITEEAM_VERSION} \
    && unzip /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip -d /tmp/ \
    && mv /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION} /opt/graviteeio-am-management-api \
    && rm -rf /tmp/*

RUN chgrp -R 0 ${GRAVITEEAM_HOME} && \
    chmod -R g=u ${GRAVITEEAM_HOME}

WORKDIR ${GRAVITEEAM_HOME}

EXPOSE 8093
VOLUME ["/opt/graviteeio-am-management-api/logs"]
CMD ["./bin/gravitee"]