#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM alpine:3.22 AS build-env
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEAM_VERSION=0

RUN apk add --update --no-cache unzip

ADD ./gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip /tmp/

RUN unzip /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip -d /tmp/ \
    && rm /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip

FROM eclipse-temurin:21.0.9_10-jre-noble
LABEL maintainer="contact@graviteesource.com"

ENV GRAVITEE_AM_HOME=/opt/graviteeio-am-management-api

# Upgrade libc6
USER root
RUN apt-get update && \
    apt-get upgrade -y libc6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupmod --new-name graviteeio ubuntu && \
 adduser --disabled-password --no-create-home -uid 1001 graviteeio --ingroup graviteeio

COPY --from=build-env --chown=1001:1000 /tmp/gravitee-am-management-api-standalone-* /opt/graviteeio-am-management-api/

WORKDIR ${GRAVITEE_AM_HOME}

EXPOSE 8093

VOLUME ["/opt/graviteeio-am-management-api/logs"]

CMD ["./bin/gravitee"]

USER graviteeio
