#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM alpine:3.22 AS build-env
LABEL maintainer="contact@graviteesource.com"

ARG GRAVITEEAM_VERSION=0

RUN apk update \
	&& apk add --update --no-cache zip unzip netcat-openbsd wget \
	&& wget --no-check-certificate  -O /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip https://download.gravitee.io/graviteeio-am/components/gravitee-am-management-api/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip \
    && unzip /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip -d /tmp/ \
    && rm /tmp/gravitee-am-management-api-standalone-${GRAVITEEAM_VERSION}.zip

FROM graviteeio/java:21-debian
LABEL maintainer="contact@graviteesource.com"

ENV GRAVITEEIO_HOME=/opt/graviteeio-am-management-api

ARG JATTACH_VERSION=2.2

# Upgrade libc6
USER root
RUN apt-get update && \
    apt-get upgrade -y libc6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends libjemalloc2 ca-certificates build-essential wget && \
    wget -O /tmp/jattach.tar.gz https://github.com/apangin/jattach/archive/refs/tags/v${JATTACH_VERSION}.tar.gz && \
    tar -xf /tmp/jattach.tar.gz -C /tmp/ && \
    make -C /tmp/jattach-${JATTACH_VERSION} && \
    JATTACH_SRC="/tmp/jattach-${JATTACH_VERSION}/jattach" && \
    if [ ! -f "${JATTACH_SRC}" ]; then \
        JATTACH_SRC="/tmp/jattach-${JATTACH_VERSION}/build/jattach"; \
    fi && \
    install -m 0755 "${JATTACH_SRC}" /usr/local/bin/jattach && \
    ln -sf /usr/lib/$(dpkg-architecture --query DEB_BUILD_MULTIARCH)/libjemalloc.so.2 /usr/lib/libjemalloc.so.2 && \
    apt-get purge -y build-essential wget && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /tmp/jattach-${JATTACH_VERSION} /tmp/jattach.tar.gz

ENV LD_PRELOAD=/usr/lib/libjemalloc.so.2

COPY --from=build-env --chown=1001:1000 /tmp/gravitee-am-management-api-standalone-* /opt/graviteeio-am-management-api/

WORKDIR ${GRAVITEEIO_HOME}
EXPOSE 8093
ENTRYPOINT ["./bin/gravitee"]

USER graviteeio
