{
 "title": "AM Gateway - Mongo",
 "time": { "from": "2024-01-05T17:18:40.144Z", "to": "2024-01-05T17:30:58.309Z" },
 "templating": {
  "list": [
   { "name": "k6_rate_interval", "query": "10s" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Access Management Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domains",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_domains {application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_apps{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Identities",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_idps{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Domain Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "abs(delta(gio_domain_evt_total{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "App Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "abs(delta(gio_app_evt_total{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Idp Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "abs(delta(gio_idp_evt_total{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Events to sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "abs(delta(gio_events_sync{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "User Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(abs(delta(gio_auth_evt_total{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (abs(delta(gio_auth_evt_total{auth_status=\"SUCCESS\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\", idp=\"internal\"}[$__interval])))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Failed Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (abs(delta(gio_auth_evt_total{auth_status=\"FAILURE\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\", idp=\"internal\"}[$__interval])))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Mongo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Connection Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, pool) (mongodb_driver_pool_size{pool=\"common-pool\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "{{ pool }} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum by (kubernetes_pod_name, pool) (mongodb_driver_pool_size{pool=\"idp-mongo\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, pool) (mongodb_driver_pool_checkedout{pool=\"common-pool\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "{{ pool }} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum by (kubernetes_pod_name, pool) (mongodb_driver_pool_checkedout{pool=\"idp-mongo\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "{{pool}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Connection Wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, pool) (mongodb_driver_pool_waitqueuesize{pool=\"common-pool\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "{{ pool }} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum by (kubernetes_pod_name, pool) (mongodb_driver_pool_waitqueuesize{pool=\"idp-mongo\", application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "{{pool}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway http throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (rate(http_server_requests_total{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway active requests & connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "req." } },
   "targets": [
    {
     "expr": "http_server_active_requests{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "req. {{kubernetes_pod_name}} ({{method}})"
    },
    {
     "expr": "http_server_active_connections{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "conn. {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway http duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(http_server_response_time_seconds_sum{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) / rate(http_server_response_time_seconds_count{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) * 1000)",
     "legendFormat": "{{kubernetes_pod_name}} "
    }
   ]
  },
  {
   "title": "Gateway http latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_response_time_seconds_sum{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\",kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) / rate(http_server_response_time_seconds_count{application=\"gio-am-gateway\", local=\"0.0.0.0:8092\", cluster=\"$cluster\",kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) * 1000",
     "legendFormat": "{{kubernetes_pod_name}} ({{method}})"
    }
   ]
  },
  {
   "title": "Gateway JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway jvm cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway system cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway system load average 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "system_cpu_count{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "max cpu load - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (jvm_memory_used_bytes{application=\"gio-am-gateway\", area=\"heap\", cluster=\"$cluster\", kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "current heap - {{ kubernetes_pod_name }} "
    },
    {
     "expr": "sum by(kubernetes_pod_name) (jvm_memory_max_bytes{application=\"gio-am-gateway\", area=\"heap\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "max heap - {{ kubernetes_pod_name }} "
    }
   ]
  },
  {
   "title": "Gateway jvm memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id, kubernetes_pod_name) (jvm_memory_used_bytes{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "{{id}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gateway jvm gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "{{cause}} - {{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Gateway jvm total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (jvm_memory_used_bytes{application=\"gio-am-gateway\", cluster=\"$cluster\", kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "Total memory - {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}