agent {
    data_dir = "/run/spire/data"
    log_level = "INFO"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/run/spire-agent/public/api.sock"
    trust_bundle_path = "/run/spire/shared/bootstrap.crt"
    trust_domain = "am.local"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "memory" {
        plugin_data {}
    }
    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
    WorkloadAttestor "docker" {
        plugin_data {}
    }
}
