server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    socket_path = "/run/spire/shared/server.sock"
    trust_domain = "am.local"
    data_dir = "/run/spire/data"
    log_level = "INFO"
    ca_ttl = "24h"
    default_x509_svid_ttl = "1h"
    default_jwt_svid_ttl = "5m"
    jwt_issuer = "http://spire-oidc:8443"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/datastore.sqlite3"
        }
    }
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "memory" {
        plugin_data = {}
    }
}
