apiVersion: v1
name: am
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 4.3.0
appVersion: 4.3.0
description: Official Gravitee.io Helm chart for Access Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio
  - oauth2
  - oidc
  - authentication
  - API
  - security
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/am?modal=changelog
  artifacthub.io/changes: |
    - Add `*.ingress.pathType` to helm/values.yaml
    - 'Database configuration has evolved to use the new gravitee.yaml organization with the repositories section'
    - 'The synchronization service is now configurable using the values.yaml'
    - 'Cache section has been introduced in the gateway configmap and is configurable using the values.yaml'
