#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

swagger: '2.0'
info:
  description: >-
    Gravitee.io - Access Management - User Session API.
    Defines User Session Endpoints exposed by AM server.
  version: 2.10.x
  title: Gravitee.io - Access Management - User Session API
  contact:
    email: contact@graviteesource.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: auth.gravitee.io
basePath: /{domain}
schemes:
  - https
paths:
  /logout:
    get:
      tags:
        - Logout
      summary: Logout user
      description: Logout current user (invalidate the HTTP session)
      parameters:
        - in: query
          name: target_url
          type: string
          description: Specifies the redirect URL after logout
        - in: query
          name: invalidate_tokens
          type: boolean
          description: Specifies if we must invalidate current user tokens
      responses:
        '302':
          description: Redirection after logout process
