#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

swagger: '2.0'
info:
  description: >-
    Gravitee.io - Access Management - Users API.
    Defines Users Endpoints exposed by AM server.

    Users endpoints are OAuth 2.0 secured and can be access either with a token with "consent_admin" scope
    or if the token 'sub' claim match the "userId" path parameter.
  version: 2.10.x
  title: Gravitee.io - Access Management - Users API
  contact:
    email: contact@graviteesource.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: auth.gravitee.io
basePath: /{domain}/users
schemes:
- https
paths:
  /{userId}/consents:
    get:
      tags:
      - Users
      summary: List user consents
      description: Lists all consents for the specified user
      produces:
      - application/json
      parameters:
      - in: query
        name: clientId
        type: string
        description: Specifies user-client consents combination
        default: 1
      responses:
        '200':
          description: A JSON object that represents a set of user consents
          schema:
            $ref: '#/definitions/UserConsents'
        '401':
          description: Invalid Token
    delete:
      tags:
      - Users
      summary: Revoke user consents
      description: Revokes all consents for a specified user
      parameters:
      - in: query
        name: clientId
        description: Revoke user's consents per application basis
      responses:
        '204':
          description: User's consents revoked
        '401':
          description: Invalid Token
  /{userId}/consents/{consentId}:
    get:
      tags:
      - Users
      summary: Get user consent
      description: Gets a consent for the specified user
      produces:
      - application/json
      responses:
        '200':
          description: A JSON object that represents a user consent
          schema:
            $ref: '#/definitions/UserConsent'
        '401':
          description: Invalid Token
        '404':
          description: Consent not found
    delete:
      tags:
      - Users
      summary: Revoke user consent
      description: Revokes one consent for a specified user
      responses:
        '204':
          description: User consent is revoked
        '401':
          description: Invalid Token
securityDefinitions:
  bearerAuth:
    type: oauth2
    tokenUrl: https://auth.gravitee.io/{domain}/oauth/token
    authorizationUrl: https://auth.gravitee.io/{domain}/authorize
    scopes:
      consent_admin: Grants consent_admin access
definitions:
  UserConsents:
    type: object
    properties:
      schemas:
        type: array
        description: Array of Strings containing URIs that are used to indicate the namespaces of the SCIM schemas.
        items:
          $ref: '#/definitions/UserConsent'
  UserConsent:
    type: object
    properties:
      id:
        type: string
        description: Consent technical id.
      userId:
        type: string
        description: User technical id.
      clientId:
        type: string
        description: OAuth 2.0 client_id.
      domain:
        type: string
        description: Security domain technical id.
      status:
        type: string
        description: Consent status.
        enum: [approved, denied]
      scope:
        type: string
        description: Scope (permission) approved/denied by the user.
      expiresAt:
        type: date
        description: Consent expiration date.
      createadAt:
        type: date
        description: Consent creation date.
      updatedAt:
        type: date
        description: Consent update date.
