name: Check Required Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required doc label
        uses: actions/github-script@v7
        with:
          script: |
              const prAuthor = context.payload.pull_request.user.login;
              const excludedBots = ['mergify[bot]', 'renovate[bot]'];
  
              if (excludedBots.includes(prAuthor)) {
              console.log(`PR was created by ${prAuthor}. Skipping label verification.`);
              return;
              }
            
              const labels = context.payload.pull_request.labels.map(l => l.name);
              const requiredLabels = ['no-docs', 'docs-needed'];
              
              // Check if at least one required label exists on the PR
              const hasRequiredLabel = requiredLabels.some(label => labels.includes(label));
              
              if (!hasRequiredLabel) {
                core.setFailed(
                  `PR is missing a documentation label! Please attach either 'no-docs' or 'doc-needs' to proceed.`
                );
              } else {
                console.log('Documentation label found. Proceeding...');
              }
